#+title:    Mangas Blacklist
#+author:   h4ss4n
#+date:     <2022-10-21 vie.>

* Index
- [[Mangas]]
  + [[Currently reading]]
  + [[On hold]]
  + [[Blacklist]]

* Mangas

** Currently reading

-

** On hold

-

** Blacklist

- *Isekai Apocalypse MYNOGHRA*: isekai, long wait chapters, bad guys side, regular history, regular drawing.
- *Tsuki Ga Michibiku Isekai Douchuu*: isekai, overpowered, lost end goal.
- *Level 1 No Saikyou Kenja*: isekai, harem, maid, academy, romance, blur +18 scenes.
- *Miyori No Nai Onnanoko*: pov, one page chapter, woman body focus, regular history, fan service.
- *Berserk of Gluttony*: leveling sytem, stagnant, mutual romance, youngters, bad history, regular drawing.
- *I signed Killing God in the Wasteland*: leveling sytem, bad history, bad drawing, difficult reading.
- *Magan to Dangan o Tsukatte Isekai o Buchinuku!*: isekai, sliced chapters, long wait chapters, snipper, saved slave girl, loli, vanilla romance, adventurer's guild, woman body focus.
- *Manchuria Opium Squad*: old times, drugs, mafia, death, torture, few +18 scenes, good story.
