#+title:    Reflexiones de la Biblia
#+author:   h4ss4n
#+date:     <2022-05-17 mar.>

* Index
- [[Conocimiento]]
  + [[Sobre la religión]]
  + [[Sobre la biblia]]
  + [[Sobre la oración]]
  + [[Sobre lo importante]]
  + [[Sobre el matrimonio]]
    - [[Relacionarse y buscar pareja en la pandemia][Relacionarse y buscar pareja]]
    - [[El costo de casarse y mantener un "hogar"][El costo de casarse]]
  + [[Sobre lo licito]]
  + [[Sobre el fanatismo]]
  + [[Sobre hábitos y perseverancia]]
  + [[Sobre el dar dinero (a la iglesia o demás)][Sobre el dar dinero]]
  + [[Sobre límites del perdón y la ayuda al prójimo][Sobre límites del perdón]]
  + [[Sobre lo laboral]]
- [[Ruta a seguir]]
  + [[Etapa llamada "el encuentro"][El encuentro]]
- [[Definiciones]]

** Conocimiento

*** Sobre la religión

- La verdadera religión no se trata de ritos y costumbres, sino de seguir el camino el Dios (buscar la verdad).
- No hagas las cosas porque los demás lo hacen.
  + la religión puede ponerte costumbres pero eso solamente no te hace una buena persona.
- Todo depende de la teoria y la prática que apliques (con tus habitos).

*** Sobre la biblia

- La biblia esta compuesta por:
  libros, capítulos y versículos
- Un ejemplo _libro_ Lucas _capitulo_ 14, _versículo_ 25

*** Sobre la oración

- Ejercitarte en la oración:
  + te llena
  + te trae paz
  + conversas con Dios
    - es como pan espiritual

*** Sobre lo importante

- La vida no solo se compone del trabajo, hay un orden:
  1. Dios
  2. tú esposa
  3. tú familia/amigos
  4. tú trabajo (estudio)
  5. tú labor en la iglesia
  6. tus amigos de la célula
  7. tus compañeros (externos)

  + hay indicadores que te ayudan a evaluar cuando haces las cosas bien, Juan 3:20-22
  + como hombres, nuestra familia come de nuestro fruto, Mateo 7:19-23
    - sea bueno o malo

*** Sobre el matrimonio

- Debes centrar tu liderazgo como hombre
- Todo dinero que entra, es para el beneficio de ambos
  + destinas para el ahorro, para poder viajar y la perspectiva de los hijos
  + necesitas encontrar a alguien que te complemente

- Cuando te casas vienes a formar una familia aparte
  + aparte de la familia en la que naciste o tus suegros

- Uno consigue una esposa no como una carga, sino para avanzar
  + puedes tener varios sueños pero no todos se van a cumplir

**** Relacionarse y buscar pareja en la pandemia

- la gente en otros lugares ya no usa mascarilla
- puede que te contagies o no (depende de ti)

**** El costo de casarse y mantener un "hogar"

- Gastos y organización
  + presupuesto de unos $20.000 desde amigos, novios, a casados
  + tienes que ahorrar para costearte la boda
    - lo ganas como soltero, guarda un 50% ($500 minimo a la semana)

*** Sobre lo licito

- "Todo me está permitido, pero no todo es provechoso; todo me está permitido, pero no todo edifica."
  1 Corintios 10:23

*** Sobre el fanatismo

- Para diferenciar el fanatismo de la verdadera doctrina tienes que aprender a discernir las cosas, diferenciar.
  + lo que dice tu conciencia (lo bueno y malo, sin una base en especifico)
  + lo que te dice Dios (en base a la palabra, te hara recordar los versiculos)
    - sin eso estamos muertos espiritualmente

- Corrige tu camino y tus actos, *no por obligación sino por convicción*
- Predica todo el tiempo, solo cuando te sea necesario *habla*
  + es diferente ser un seguidor, de ser un discipulo

*** Sobre hábitos y perseverancia

- Todo buen habito, fortalecelo y no lo abandones.
  + No se trata de quien empezo antes, sino de cuanta dedicación pones (ser más diligente).

- La persona necesita tener una madurez espiritual.
   + se refleja en sus acciones (y palabras) y estilo de vida
   + analizar cuidadosamente

- Como actuarias sino existieran los espejos/reflejos? como te percibirías?
  + solo actuarias por lo que dicen los demás
  + actuarias por tus instintos

- Tienes que cambiar tu forma de pensar:
  + personal
  + laboral
  + financiera

*** Sobre el dar dinero (a la iglesia o demás)

- Hay tres formas de dar dinero:
  + limosna (caridad al pobre)
  + ofrenda (es voluntario, lo que tu quieras)
  + diezmo (no te lo pide la iglesia)

- Ser bueno no es igual a ser pobre.
- Vas primero por el lado espiritual (y lógico), luego va la biblia

*** Sobre límites del perdón y la ayuda al prójimo

- Si tu practicas el perdón, tu corazón estará libre de resentimientos.
  + porque si guardas rencor te haces daño a ti mismo

- El perdón hazlo siempre una y otra vez, independientemente de lo que te hagan (del tiempo o época).
  + es como una fuente de agua pura que fluye de ti (perdón, amor y compasión)
    - manten tu corazón puro, donde no fluya maldad que lo ensucie (odio, amargura, venganza)
    - lo haces por tu propio bien y por obediencia a Dios.
  + no hacerlo provoca que vuelvas a caer en los mismos problemas del pasado.
    - el que se hace daño eres tú
- Es diferente perdonar a alguien y otra cosa dejar que lo vuelva a hacer.
  + no dejes que se aprovechen de ti (o te falten el respeto).
  + diles que lo(s) perdonas, pero les explicas que *no es correcto lo que están haciendo*
    - lo apasiguas, diciendole que las cosas no se hace de esa manera
    - si la persona entiende el consejo, has logrado ayudar a la persona.
  + si la persona es necia o malagradecida y no quiere entender, solo te queda apartarte.
    - es importante alejarse de las personas que no se ayudan
    - evita "generar" heridas que tengas que perdonar
    - no caigas en un ciclo vicioso o *mal hábito* (te lastiman, te curas... y vuelves a dejar que te lastimen)
    - *no tiene sentido*, evita que te lastimen
  + no dejes que la situación o personas te afecten o te lleven a pecar

- Cuando ayudas, para evitar que las personas se tomen la confianza/costumbre de estarte pidiendo (a cada rato) y luego quieran irrespetarte.
  + sigue el hábito de *ayudar cuando puedas y hasta donde puedas*
  + no des a entender a la persona que eres su fuente de ayuda o que lo vas a mantener
    - en vez de eso, los guias a donde los pueden ayudar (como fuente o canal)
    - apoyate en la iglesia, existen ministerios que ayudan a la pobre o en necesidad (*CONSEGUIR CONTACTO*)
    - les ayudas en un inicio y luego les guias a un lugar donde los pueden ayudar más

    - "si te piden una vez para comer (y vez que hacen el esfuerzo) les ayudas,
      si te piden una segunda ocasión les dices que les daras su contacto a una iglesia,
      para que les ubiquen y les ayuden"

    - hay ministerios de la iglesia que incluso puede enseñarles a trabajar o darles un trabajo
    - es hasta ahi es una manera *prudente* para ayudar a alguien que tiene muchas necesidades,
      y que necesita que alguien le ayude a levantarse
  + si la persona no quiere ir a la iglesia, trabajar, hacer un esfuerzo y solo le gusta pedir
    - aunque te cueste, les dices:
      "si su intención no es superarse,
      no va a poder salir de esa situación...
      con su permiso" y te vas.
    - no es una obligación, sino una elección tuya
- De esa manera haces una buena acción, ayudas, pero tampoco te haces cargo de una persona o necesidades que no te corresponden (evitando el desgaste emocional).


*** Sobre lo laboral

- Existen oportunidades que se presentan y otras que tienes que crearlas
  + el tiempo que se dedicaría a hacer un plano (8 horas)
    - se la pasa buscando a un cliente y aprendiendo marketing
    - cuando se cierra una negociación/contrato se pide un anticipo
  + se enfoca mas en la administración que en la producción
    - consigues pasantes, la moneda de cambio es el conocimiento
    - se lleva un control sobre las personas que producen
    - en dados casos te pones a cargo de la producción (cuando es algo mas complicado)

- Dedica 3 horas diarias para marketing (investigar/aprender)
  + para vender tus servicios (redes sociales instagram)
- busca clientes que no regateen, que gastan en cosas caras
  + $3 a $3.5 el m2
  + a veces máximo $650 quieren pagar en una constructora
- busca en compañias
- hay maneras de sacar provecho
  + hay otros atajos donde puedes buscar tus objetivos

- Tienes 2 opciones: o te lanzas o no lo haces
  + pero sino te arriesgas, pierdes por no intentarlo (por anticipado)
  + tienes que evaluar si el riesgo es equivalente a lo que vas a ganar
    - cuando te lanzas a ofrecer algo que no sabes, tienes que ir con una estrategia para poder atacar el problema

- Si encuentras una oportunidad y puede servir a que crezcas, hazlo
  + analiza el trabajo
    - puede relacionarse un conocimiento (habilidad) que aprendas, con algo que hagas en el futuro
  + aprendes y luego buscas como potenciarte mas
    - piensa: "ellos tienen una necesidad y yo tengo el conocimiento"
    - pueden suceder obstáculos (pandemia, paros, etc) y equivocaciones, pero sigues adelante

- Te ayuda a sentirte capaz de abrir una empresa/emprendimiento
  + cuando quedas bien con los clientes, ellos te contratan mas o recomiendan
  + cuando tienes la necesidad, le dedicas una hora bien invertida (si tienes mas mejor)


-------------
Agregar
-------------

"no esperes de los demás, si lo hacen es un extra,
asi no te decepcionaras de las expectaticas o reciprocidad que esperas de ellos" "con el perdón, no pagas mal por mal...
asi demuestras con tus acciones que no respondes de la misma manera, que eres diferente"

Romanos 12-16 a 12-21

Hay dos mundos el espiritual y el natural. Los demonios se disfrazan de libertad (vicios).

No es una religión (un grupo de personas que se reunen y ya), sino una relación personal con Dios.
-lo que queda en tu corazón

te divides en cuerpo, alma y espiritu
-quien vive en ti es el espiritu (como la tercera persona)

Un fruto no puede nacer por si solo, sino hay arbol que lo produzca.
Gálatas 5:22-23



Durante la oración mantenerte en cuentas, y arrepentirte de tus equivocaciones
- "Perdoname, este dia yo cometi esto <inserta pecado aqui> de cosas que haces conciente o inconcientemente
  (de las que te das cuenta una vez que te equivocaste)
- tu meta es mantenerte puro
  + los cristianos buscan llegar de lo bueno a lo mejor, de lo mejor a la excelencia y de la excelencia a la perfección
  + tal vez no tengas una vida perfecta, pero estaras más cerca de él
- el pecado te separa de Dios (como un cortocircuito)
  + los vicios tienes que cortarlos de raiz, porque al hacerlo poco a poco (la mente o vista -sentidos en general-),
    te pueden engañar y terminarias no dejandolo (volviendo a caer)


24 ¿No se dan cuenta de que en una carrera todos corren, pero solo una persona se lleva el premio? ¡Así que corran para ganar! 25 Todos los atletas se entrenan con disciplina. Lo hacen para ganar un premio que se desvanecerá, pero nosotros lo hacemos por un premio eterno. 26 Por eso yo corro cada paso con propósito. No solo doy golpes al aire. 27 Disciplino mi cuerpo como lo hace un atleta, lo entreno para que haga lo que debe hacer. De lo contrario, temo que, después de predicarles a otros, yo mismo quede descalificado.
1 Corintios 9


** Ruta a seguir

- Cada uno elige lo que quiere hacer con su futuro (planifícalo), vale la pena esperar.
- El camino de la vida
  + seguir el sendero correcto (no el que todos siguen)

*** Etapa llamada "el encuentro"
- cambia tu vida, sucede una sola vez
- vas a una lugar apartado (tipo retiro espiritual un fin de semana)
- te desconectas de todo trabajo, estudio, etc
- "vi a Dios cara a cara y cambio mi alma", sientes su presencia
  + siempre que tu estes dispuesto a ir, no hay problema (cuesta $25)
  + tienes que ir de corazón y regresas con el corazon limpio


** Definiciones

- *Cristo*: significa Mesías, salvador/liberador de la humanidad que traerá paz instaurando el Reino de Dios.
