#+title:    Islam Faith
#+author:   h4ss4n
#+date:     <2023-09-16 sáb.>

* Index
- [[Pillars][Pillars]]
- [[Quran][Quran]]
  + [[Rules][Rules]]
  + [[Trinity][Trinity]]
- [[Hadith][Hadith]]
- [[Sects][Sects]]
- [[Culture][Culture]]

* Content

** Pillars


** Quran

- Words between brackets in the Quran is not part of it (added later for reader understanding).
- Any muslim claim against the Quran, it turn them in /kaafir/ immediately.

*** Rules

*** Preservation

- *In response of:* Enemies of Islam corrupting the Quran
  + *The problem:* The claim contradicts the Quran

    Allah promise to protect his holy books (Bible and Torah included) >> (Tafsir al-Jalalayn, Quran, Chapter 15, Verse 9)


- *In response of:* Quran perfect preservation until today
  + *The problem:* Their own sources debunk that claim

    Muhammad didn't perfectly memorise the Quran >> (Sahih al-Bukhari 5037; Book 66, Hadith 60)

    The collections that were made by the companions of Muhammad were not identical >> Quran, Chapter 92, Verse 3) vs (Sahih al-Bukhari 4944; Book 65, Hadith 465)

    All this Qurans with different meanings (not just grammatical errors) led to almost a civil war forcing the third caliph Uthman, to choose one of these collections and burn the others >> (Sahih al-Bukhari 4987; Book 66, Hadith 9)

    Although a large number of pre-1924 Qurans were destroyed again by dumping them in the river Nile because still didn't match the meaning, leaving us with the 1924 Egyptian Standard Edition of the Quran as we known today >> (Reynolds, Gabriel Said (2008). "Introduction: Qur'anic Studies and its Controversies")

    Finally the problem with 'Hafs Ibn Abi Dawud Al Kufi' as the transmitter of that Quran, being accused by muslims scholars to be a fraud, thief and liar >> (Ibn Hijr, Tahtheeb-Al-Tahtheeb, Volume 2, p. 245)

    _NOTE:_ In the web page of 'easyquranstore', they have 13 versions of the Quran in Arabic or in the web page 'daralfiker' in Jordan has over 20 Arabic versions of the Quran for sale, so we can see why the ancient Uthmanic Quran manuscripts aren't identical to the modern Quran (Samarqand MSS VS 1924 Egyptian Edition).

*** Quran Only Muslims

- *The problems:*
  + ¿When (year) and where (place) was send down the Quran?
  + ¿How much to pay for charity?
  + ¿Where it's say Jibril is an angel?

*** Trinity

- *In response of:* 1 + 1 + 1 = ?
  + *The problem:* The claim contradicts the Quran

    In the same verse that says 'no trinity,' it confirms the opposite >> (John, Chapter 1, Verses 1-14) vs (Quran, Chapter 4, Verse 171)
    Jesus is portrayed as:
    1. a messenger (man)
    2. His Word
    3. a spirit proceeding


- *In response of:* Christians worship 3 gods (as [[file:~/org/bible/polemics/islam/muhammad/muhammad.org::Polytheism nº1][pagans]])
  + *The problem:* The claim contradicts the Quran

    The Quran says Christian believe that Allah & Jesus are one, which means there is not 2nd god, or 3rd god >> (Quran, Chapter 5, Verse 17) (Quran, Chapter 5, Verse 72)

  + *The problem:* The Quran contradicts the Quran

    Also the Quran in other verse claims that the trinity consists in three gods Allah, Mary and Jesus>> (Quran, Chapter 5, Verse 116)
    ¿So Allah didn't know what Christian worship (Father, Son & Holy Ghost)? but supposedly he is all-knowing.

*** Isa (Jesus)

- *In response of:* How to worship a God who came from a female private part?
  + But at the same time their book says Jesus is Holy >> (Quran, Chapter 19, Verse 19)
  + The irony that Muhammad maked wudu in [[file:~/org/bible/polemics/islam/muhammad/muhammad.org::Unholiness][filth]]

- *In response of:* Christians are sons of God like Jesus?
  + *The answer:* We're not the same as Jesus, but spiritual sons >> (Matthew, Chapter 6, Verses 9-13)

** Hadith

To prove the authenticity:
1. Check the chain of narration
2. Check the sana (year) & marja' (source to imitate/follow" or "religious reference")
   - when both are authentic (it's clasified as "sahih" hadith)
3. Check the story (content)

*** Scholars

If the hadith contradict the Quran, muslims didn't take the hadith.
Question to make:
- ¿Can you show me from your scholars (even the modern ones) who say that?

_NOTE:_ Shias don't go with Hadith al-Bukhari or Muslim

** Sects

*** Sunni

*** Shia


** Culture

*** Past

*** Today
