#+title:    Analisis de la Biblia
#+author:   h4ss4n
#+date:     2022-08-15 lun

* Antiguo Testamento

Desde el libro de Genesis hasta Mateo

* Nuevo Testamento

Desde el libro de Mateo hasta Apocalipsis

** Cap. 1-2
- porque se recibia todo mensaje en sueños?
- porque tomarse todo el trabajo de hacer las cosas de esa manera, si dios pudo proveer a jesus de un nacimiento mas tranquilo y menos tumultoso?
- porque los judio no aceptaron al nuevo mesias? si sus textos tenian relacion con el antiguo testamento, eso no estaba predicho ahi?


** Cap. 3-4
- de los pecado pasados y limpiados por el bautismo, se aconseja hacer frutos dignos del arrepentimiento (del inicio de sus nuevas vidas, despeus de haber visto la verdad), y no pensar que podran engañar con ello a su creador (mostrando/diciendo una cosa y actuando de otra manera)
- "todo árbol que no da buen fruto es cortado y echado en el fuego" (habla sobre el juicio final que vendra a todos)
  + incluso Jesús se bautizo por Juan, para mostrar que todos tenian que pasar por la ceremonia (nadie estaba excento)
- habla sobre la tentacion
  + el hombre no solo vive de sustento fisico, sino espiritual
  + no es correcto hacer duda sobre la existencia del creador mediante pruebas
  + sobre solo adorar y servir al creador
- habla sobre el arrepentimiento de los pecados (ya que el juicio se acerca)


** Cap. 5-6
- habla sobre quienes seran bienaventurados
  + personas buenas y que sufren distinta clase de males (incluso los pobres en espíritu)
  + comparacion que los que mas padecen por defender una posicion correcta, seran mejor recompensados al final
- sobre la luz propia que alumbra a los demas, reflejadas por las obras propias, como una representación de su creador
  + y el cumplimiento de todas las leyes por muy pequeñas que parezcan
- coinciliar la paz propia antes de entablar contacto con el señor
- el pecado (ejm: adulterio) se comete primero con la mente antes de la acción
  + explicacion mejor sobre el divorcio?
- sobre no hacer juramentos en vano
  + preferiblemente no hacerlos
- poner la otra mejilla (aplica en la practica)
  + habla sobre el poco esfuerzo que es amar a quienes te aman, pero distinto hacerlo por tus enemigos
- sobre ayudar (ejm: dar limosna), ayunar u orar en secreto, ya que tiene mas valor
- sobre hacer tesoro en el cielo, mas que en la tierra (alegoria a las acciones)
  + "Porque donde esté vuestro tesoro, allí estará también vuestro corazón."
- sobre que no es posible servir al creador y a las riquezas al mismo tiempo
- sobre que no es bueno tener afan al por venir (comida, bebida, vestimenta, etc), concentrarse en el dia a dia (que el señor proveera)


** Cap. 7
- sobre no juzgar a los demas, porque se te juzgara de igual forma y antes de ver el mal en los demas, mirarse primero en un espejo
  - tambien de no desperdiciar algo valioso a quien no lo sabe apreciar (tiempo, conocimiento, etc)
- duda sobre: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá."?
- Sobre el concepto de la 'puerta estrecha'
  + "Entrad por la puerta estrecha; porque ancha es la puerta, y espacioso el camino que lleva a la perdición, y muchos son los que entran por ella; porque estrecha es la puerta, y angosto el camino que lleva a la vida, y pocos son los que la hallan."
- "Guardaos de los falsos profetas, que vienen a vosotros con vestidos de ovejas, pero por dentro son lobos rapaces. Por sus frutos los conoceréis." a que se refiere a falsos profetas? (mentirosos? estafadores?)
  + sobre los aduladores que solo hablan pero no actuan
- Sobre saber escuchar consejos "Cualquiera, pues, que me oye estas palabras, y las hace, le compararé a un hombre prudente, que edificó su casa sobre la roca."


** Cap. 8
- jesus curo a un leproso, y le dijo que no lo mencione a nadie, sino que vaya y lo muestre a un sacerdote y haga la ofrenda que hizo Moises?
- sobre que paso con el criado del centurion que necesitaba ayuda?
- sobre los que querian seguir a jesus?? (no queda muy claro lo que se referia con los muertos)
- sobre ser hombres de poca fe (cuando calmo los vientos y el mar)
- sobre los endemoniados gadarenos y como los espanto? (no es muy claro que significa eso)


** Cap. 9
- "¿Por qué pensáis mal en vuestros corazones? Porque, ¿qué es más fácil, decir: Los pecados te son perdonados, o decir: Levántate y anda?"
- Pues para que sepáis que el Hijo del Hombre tiene potestad en la tierra para perdonar pecados"
- Cuando se sentaron publicanos (¿?) y pecadores a comer en la mesus junto a jesus, fue criticado y dijo:
  + "Los sanos no tienen necesidad de médico, sino los enfermos"
  + "Misericordia quiero, y no sacrificio. Porque no he venido a llamar a justos, sino a pecadores, al arrepentimiento."
- sobre el ayuno
- "tu fe te ha salvado"
- "Conforme a vuestra fe os sea hecho"
- "Y al ver las multitudes, tuvo compasión de ellas; porque estaban desamparadas y dispersas como ovejas que no tienen pastor."


** Cap. 10
- "Entonces llamando a sus doce discípulos, les dio autoridad sobre los espíritus inmundos (¿?), para que los echasen fuera, y para sanar toda enfermedad y toda dolencia."
- "Por camino de gentiles no vayáis, y en ciudad de samaritanos no entréis, sino id antes a las ovejas perdidas de la casa de Israel."
  + "Sanad enfermos, limpiad leprosos, resucitad muertos, echad fuera demonios; de gracia recibisteis, dad de gracia."
  + "No os proveáis de oro, ni plata, ni cobre en vuestros cintos; ni de alforja para el camino, ni de dos túnicas, ni de calzado, ni de bordón; porque el obrero es digno de su alimento."
    - "Y si la casa fuere digna, vuestra paz vendrá sobre ella; mas si no fuere digna, vuestra paz se volverá a vosotros. Y si alguno no os recibiere, ni oyere vuestras palabras, salid de aquella casa o ciudad, y sacudid el polvo de vuestros pies."
- "He aquí, yo os envío como a ovejas en medio de lobos; sed, pues, prudentes como serpientes, y sencillos como palomas."
- "Y no temáis a los que matan el cuerpo, mas el alma no pueden matar; temed más bien a aquel que puede destruir el alma y el cuerpo en el infierno."
  + "Y a cualquiera que me niegue delante de los hombres, yo también le negaré delante de mi Padre que está en los cielos."
- Jesús, causa de división
  + "No penséis que he venido para traer paz a la tierra; no he venido para traer paz, sino espada."
  + "El que halla su vida, la perderá; y el que pierde su vida por causa de mí, la hallará."


** Cap. 11
- Mensaje a Juan el Bautista
  + se cura todos los malos a los enfermos, "y a los pobres es anunciado el evangelio"?
  + que relevenacia tenia Juan el Bautista, previo la aparición de Jesús?? (profeta? mensajero?)
    - sobre las criticas hacia el (estaba en la carcel?)
- a pesar que ciertas ciudades presenciaron los milagros de Jesús no se 'arrepintieron de sus pecandos'
  + se menciona que seran castigadas mas que Sodoma porque ahi reinaba al menos la ignorancia/maldad para justificar sus actos
- "Te alabo, Padre, Señor del cielo y de la tierra, porque escondiste estas cosas de los sabios y de los entendidos, y las revelaste a los niños."??
  + "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar. Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón; y hallaréis descanso para vuestras almas; porque mi yugo es fácil, y ligera mi carga." (cual era su carga?)


** Cap. 12
- "hacen lo que no es lícito hacer en el día(s) de reposo"?? (ayunas?)
  + usar la logica sobre necesidades basicas
    - es lícito hacer el bien
- porque se menciona que pasara desapercibido y jesus sera discreto? en cuanto a su labor/estatus?
- "Todo reino dividido contra sí mismo, es asolado, y toda ciudad o casa dividida contra sí misma, no permanecerá.
  + "El que no es conmigo, contra mí es; y el que conmigo no recoge, desparrama."
  + "Todo pecado y blasfemia será perdonado a los hombres; mas la blasfemia contra el Espíritu no les será perdonada."
  + "O haced el árbol bueno, y su fruto bueno, o haced el árbol malo, y su fruto malo; porque por el fruto se conoce el árbol"
    - "¿Cómo podéis hablar lo bueno, siendo malos? Porque de la abundancia del corazón habla la boca."
- "La generación perversa demanda señal" (algun indicativo que pruebe divino sendero? poder?)
- "El espíritu inmundo que vuelve"


** Cap. 13
- Jesús hablabla a las personas que se reunian a escuharlo solo en *Párabolas*
  + les dio a entender a sus dicipulos que mientas ellos podian comprender el reino de los cielos
  + el resto de personas no tenias ese entendimiento
    - "porque viendo no ven, y oyendo no oyen, ni entienden"
    - De manera que se cumple en ellos la profecía de Isaías, que dijo:
      "De oído oiréis, y no entenderéis;
      Y viendo veréis, y no percibiréis.
      Porque el corazón de este pueblo se ha engrosado,
      Y con los oídos oyen pesadamente,
      Y han cerrado sus ojos;
      Para que no vean con los ojos,
      Y oigan con los oídos,
      Y con el corazón entiendan,
      Y se conviertan,
      Y yo los sane."
- Parábolas referidas:
  + P. del sembrador
  + P. del trigo y la cizaña
  + P. de la semilla de mostaza
  + P. de la levadura
  + P. del tesoro escondido
  + P. de la perla de gran precio
  + P. de la red
- "Abriré en parábolas mi boca;
  Declararé cosas escondidas desde la fundación del mundo."
  + RELEER las parábolas para entender mejor


** Cap. 14
- Matan a Juan el Bautista
- Jesús realiza el milagro de multiplicar la comida para 5000 y mas personas
- Jesús realiza el milagro de caminar sobre el agua


** Cap. 15
- "Este pueblo de labios me honra;
  Mas su corazón está lejos de mí.
  Pues en vano me honran,
  Enseñando como doctrinas, mandamientos de hombres."
- Parábola: "son ciegos guías de ciegos; y si el ciego guiare al ciego, ambos caerán en el hoyo."
  + Habla acerca del veneno que puede salir de la boca para hacer perder el camino de la gente, incluso cometer pecados (malos pensamientos, los homicidios, los adulterios, las fornicaciones, los hurtos, los falsos testimonios, las blasfemias, etc).
- RELEER La fe de la mujer cananea


** Cap. 16
- La demanda de una señal??
  + "La generación mala y adúltera demanda señal; pero señal no le será dada, sino la señal del profeta Jonás."
- Jesús habla sobre cuidarse de "la doctrina de los fariseos y de los saduceos."
- Jesús habla sobre edificar su iglesia y de darles las llaves de las puertas del cielo a Pedro.
- Jesús anuncia su muerte, y les dice a sus dicipulos:
  "Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame. Porque todo el que quiera salvar su vida, la perderá; y todo el que pierda su vida por causa de mí, la hallará. Porque ¿qué aprovechará al hombre, si ganare todo el mundo, y perdiere su alma? ¿O qué recompensa dará el hombre por su alma?"


** Cap. 17
- Jesús hablo en un monte con Moises y Elias (era Juan el bautista? un profeta que mataron sin saber)
  + les pidio a sus discipulos que no hablen de los visto hasta su resurreccion.
- Con fe nada sera imposible? (se necesita oracion y ayuno)


** Cap. 18
- ¿Quien es el mayor en el reino de los cielos?
  + hace su comparacion con un niño (inocencia?) vs sus discipulos
- Habla que es preferible perder un ojo, mano o pie, que estar completo, si estos te llevan a cometer pecados.
- Parábola de la oveja perdida
- "... si tu hermano peca contra ti, ve y repréndele estando tú y él solos; si te oyere, has ganado a tu hermano."
  + "... todo lo que atéis en la tierra, será atado en el cielo; y todo lo que desatéis en la tierra, será desatado en el cielo."
- historia sobre el señor y la deuda del siervo y el consiervo (siervo del siervo)
  + "... perdonáis de todo corazón cada uno a su hermano sus ofensas"


** Cap. 19
- Jesús habla sobre el divorcio:
  "Por esto el hombre dejará padre y madre, y se unirá a su mujer, y los dos serán una sola carne?
  Así que no son ya más dos, sino una sola carne; por tanto, lo que Dios juntó, no lo separe el hombre."
  + "... cualquiera que repudia a su mujer, salvo por causa de fornicación, y se casa con otra, adultera; y el que se casa con la repudiada, adultera."
  + "No todos son capaces de recibir esto" (matrimonio?)...  "sino aquellos a quienes es dado." ... "El que sea capaz de recibir esto, que lo reciba."
- De los niños es el reino de los cielos (por su inocencia?)
- Para entrar al reino de los cielos, llevar a cabo los mandamientos:
  No matarás.
  No adulterarás.
  No hurtarás.
  No dirás falso testimonio.
  Honra a tu padre y a tu madre.
  Amarás a tu prójimo como a ti mismo.
  + "es más fácil pasar un camello por el ojo de una aguja, que entrar un rico en el reino de Dios"


** Cap. 20
- Los obreros de la viña (comparación con el reino de los cielos)
  + se conviene pagar/recompensar de cierta forma y a las personas aceptar o no
- Jesús anuncia su muerte por 3ra vez.
- "Sabéis que los gobernantes de las naciones se enseñorean de ellas, y los que son grandes ejercen sobre ellas potestad. Mas entre vosotros no será así, sino que el que quiera hacerse grande entre vosotros será vuestro servidor, y el que quiera ser el primero entre vosotros será vuestro siervo; como el Hijo del Hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos."


** Cap. 21
- Jesús sabia que le deparaba el futuro, es adelantaba a los acontecimientos.
- Como fuente de sus milagros, revelaba "Y todo lo que pidiereis en oración, creyendo, lo recibiréis."
- Parábola de los dos hijos
  + Análisis sobre hacer las cosas, de mala manera y no hacerlas en absoluto?
- Parábola Los labradores malvados
  + "La piedra que desecharon los edificadores,
    Ha venido a ser cabeza del ángulo."
    "... Por tanto os digo, que el reino de Dios será quitado de vosotros,
    y será dado a gente que produzca los frutos de él."


** Cap. 22
- Parábola de la fiesta de bodas
  + "Las bodas a la verdad están preparadas; mas los que fueron convidados no eran dignos."
- De Jesús era dicho que era amante de la verdad, y que enseñaba con la verdad el camino de Dios. Y con eso trataba a todos, ya que no juzgaba por la apariencia (alcurnia) de los hombres.
- "... en la resurrección ni se casarán ni se darán en casamiento, sino serán como los ángeles de Dios en el cielo"
- "Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente. Este es el primero y grande mandamiento. Y el segundo es semejante: Amarás a tu prójimo como a ti mismo. De estos dos mandamientos depende toda la ley y los profetas."
*** ¿De quién es hijo el Cristo?
- RELEER y ANALIZAR este verso.


** Cap. 23
- "... el que se enaltece será humillado, y el que se humilla será enaltecido."
  + los escribas y fariseos actuaban mal hace un buen tiempo??
  + los llamaba hipócritas, decia que: "cerráis el reino de los cielos delante de los hombres; pues ni entráis vosotros, ni dejáis entrar a los que están entrando."
- "Pues el que jura por el altar, jura por él, y por todo lo que está sobre él; el que jura por el templo, jura por él, y por el que lo habita; y el que jura por el cielo, jura por el trono de Dios, y por aquel que está sentado en él."
  + "¡Guías ciegos, que coláis el mosquito, y tragáis el camello!" ??
  + "¡Serpientes, generación de víboras!"
- Decia "envío profetas y sabios y escribas; y de ellos, a unos mataréis y crucificaréis, y a otros azotaréis en vuestras sinagogas, y perseguiréis de ciudad en ciudad".


** Cap. 24
- "... y por haberse multiplicado la maldad, el amor de muchos se enfriará. Mas el que persevere hasta el fin, este será salvo."
  + Jesús habla sobre lo que vendra antes del fin, de las guerras y desastres venideros, asi como falsos profetas
  + Se necesita contexto para la frase "... cuando veáis en el lugar santo la abominación desoladora de que habló el profeta Daniel... "
- La venida del Hijo del Hombre
  + "E inmediatamente después de la tribulación de aquellos días, el sol se oscurecerá,
    y la luna no dará su resplandor, y las estrellas caerán del cielo,
    y las potencias de los cielos serán conmovidas.
    Entonces aparecerá la señal del Hijo del Hombre en el cielo;
    y entonces lamentarán todas las tribus de la tierra,
    y verán al Hijo del Hombre viniendo sobre las nubes del cielo, con poder y gran gloria.
    Y enviará sus ángeles con gran voz de trompeta, y juntarán a sus escogidos,
    de los cuatro vientos, desde un extremo del cielo hasta el otro."
- Habla de la Parábola de la higuera, y como todo acontecera en el momento menos esperado.
  + pero que las señales seran el aviso de lo que esta por venir
  + asi mismo tomaran por sorpresa a los que hacen el bien y el mal
    + Referencia al RAPTO!?


** Cap. 25 (por leer Cap. 26)
- Parábola de las diez vírgenes
- Parábola de los talentos
  + a que se refiere con talentos? es dinero??
- Habla de como se hara un juicio en las naciones, separando los buenos de los malos
  + y quienes ayudaron a los necesitados, como si se Jesús se tratara recibiran la gloria
  + mientras los que hicieron lo contrario, seran castigados


** Adicional

*** Etapa llamada "el encuentro"
- cambia tu vida, sucede una sola vez
- vas a una lugar apartado (tipo retiro espiritual un fin de semana)
- te desconectas de todo trabajo, estudio, etc
- "vi a dios cara a cara y cambio mi alma", sientes su presencia
  + siempre que tu estes dispuesto a ir, no hay problema (cuesta $25)
  + tienes que ir de corazon y regresas con el corazon limpio

- si tu guardas rencor te haces daño a ti mismo


*** Canciones

**** Cantante:
Jesús Adrián Romero

**** Canción:
- El aire de tu casa
  + querer percibir su presencia al estar cerca y ser su amigo

- Que seas mi universo
  + buscar que el señor sea parte de tu vida/existencia (agape)


** Fuentes

+ [[https://my.bible.com/es/bible/149/MAT.3.RVR1960]]
