#+title:    Analisis de la Biblia
#+author:   h4ss4n
#+date:     <2022-08-15 lun.>

* Index
- [[Antiguo Testamento]]
- [[Nuevo Testamento]]
  + [[Evangelio S. Mateo]]
  + [[Evangelio S. Marcos]]
  + [[Evangelio S. Lucas]]

* Antiguo Testamento

Desde el libro de Génesis hasta Mateo.

* Nuevo Testamento

Desde el libro de Mateo hasta Apocalipsis.

** Evangelio S. Mateo

*** Cap. 1-2
- Por qué todos los mensajes eran recibidos mediante sueños?
- Por qué tomarse todo el trabajo de hacer las cosas de esa manera, si Dios pudo proveer a Jesús de un nacimiento mas tranquilo y menos tumultoso?
- Por qué los judío no aceptaron al nuevo mesias? si sus textos tenian relación con el antiguo testamento, eso no estaba predicho ahi?

*** Cap. 3-4
- De los pecado pasados y limpiados por el bautismo, se aconseja hacer frutos dignos del arrepentimiento (del inicio de sus nuevas vidas, despeus de haber visto la verdad), y no pensar que podran engañar con ello a su creador (mostrando/diciendo una cosa y actuando de otra manera)
- Jesús dice:
  "todo árbol que no da buen fruto es cortado y echado en el fuego" (habla sobre el juicio final que vendra a todos)
  + incluso Jesús se bautizo por Juan, para mostrar que todos tenian que pasar por la ceremonia (nadie estaba excento)
- Habla sobre la tentación
  + el hombre no solo vive de sustento fisico, sino espiritual
  + no es correcto hacer duda sobre la existencia del creador mediante pruebas
  + sobre solo adorar y servir al creador
- Habla sobre el arrepentimiento de los pecados (ya que el juicio se acerca)

*** Cap. 5-6
- Habla sobre quienes seran bienaventurados
  + personas buenas y que sufren distinta clase de males (incluso los pobres en espíritu)
  + comparacion que los que mas padecen por defender una posicion correcta, seran mejor recompensados al final
- Sobre la luz propia que alumbra a los demas, reflejadas por las obras propias, como una representación de su creador
  + y el cumplimiento de todas las leyes por muy pequeñas que parezcan
- Coinciliar la paz propia antes de entablar contacto con el señor
- El pecado (ejm: adulterio) se comete primero con la mente antes de la acción
  + explicacion mejor sobre el divorcio?
- Sobre no hacer juramentos en vano
  + preferiblemente no hacerlos
- Poner la otra mejilla (aplica en la practica)
  + habla sobre el poco esfuerzo que es amar a quienes te aman, pero distinto hacerlo por tus enemigos
- Sobre ayudar (ejm: dar limosna), ayunar u orar en secreto, ya que tiene mas valor
- Sobre hacer tesoro en el cielo, mas que en la tierra (alegoria a las acciones)
  + "Porque donde esté vuestro tesoro, allí estará también vuestro corazón."
- Sobre que no es posible servir al creador y a las riquezas al mismo tiempo
- Sobre que no es bueno tener afan al por venir (comida, bebida, vestimenta, etc), concentrarse en el dia a dia (que el señor proveera)

*** Cap. 7
- Sobre no juzgar a los demas, porque se te juzgara de igual forma y antes de ver el mal en los demas, mirarse primero en un espejo
  + tambien de no desperdiciar algo valioso a quien no lo sabe apreciar (tiempo, conocimiento, etc)
- Duda sobre: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá."?
- Sobre el concepto de la 'puerta estrecha'
  + "Entrad por la puerta estrecha; porque ancha es la puerta, y espacioso el camino que lleva a la perdición, y muchos son los que entran por ella; porque estrecha es la puerta, y angosto el camino que lleva a la vida, y pocos son los que la hallan."
- "Guardaos de los falsos profetas, que vienen a vosotros con vestidos de ovejas, pero por dentro son lobos rapaces. Por sus frutos los conoceréis." a que se refiere a falsos profetas? (mentirosos? estafadores?)
  + sobre los aduladores que solo hablan pero no actuan
- Sobre saber escuchar consejos "Cualquiera, pues, que me oye estas palabras, y las hace, le compararé a un hombre prudente, que edificó su casa sobre la roca."

*** Cap. 8
- Jesús curo a un leproso, y le dijo que no lo mencione a nadie, sino que vaya y lo muestre a un sacerdote y haga la ofrenda que hizo Moises?
- sobre que paso con el criado del centurion que necesitaba ayuda?
- sobre los que querian seguir a Jesús?? (no queda muy claro lo que se referia con los muertos)
- sobre ser hombres de poca fe (cuando calmo los vientos y el mar)
- sobre los endemoniados gadarenos y como los espanto? (no es muy claro que significa eso)

*** Cap. 9
- "¿Por qué pensáis mal en vuestros corazones? Porque, ¿qué es más fácil, decir: Los pecados te son perdonados, o decir: Levántate y anda?"
- Pues para que sepáis que el Hijo del Hombre tiene potestad en la tierra para perdonar pecados"
- Cuando se sentaron publicanos (¿?) y pecadores a comer en la mesus junto a Jesús, fue criticado y dijo:
  + "Los sanos no tienen necesidad de médico, sino los enfermos"
  + "Misericordia quiero, y no sacrificio. Porque no he venido a llamar a justos, sino a pecadores, al arrepentimiento."
- sobre el ayuno
- "tu fe te ha salvado"
- "Conforme a vuestra fe os sea hecho"
- "Y al ver las multitudes, tuvo compasión de ellas; porque estaban desamparadas y dispersas como ovejas que no tienen pastor."

*** Cap. 10
- "Entonces llamando a sus doce discípulos, les dio autoridad sobre los espíritus inmundos (¿?), para que los echasen fuera, y para sanar toda enfermedad y toda dolencia."
- "Por camino de gentiles no vayáis, y en ciudad de samaritanos no entréis, sino id antes a las ovejas perdidas de la casa de Israel."
  + "Sanad enfermos, limpiad leprosos, resucitad muertos, echad fuera demonios; de gracia recibisteis, dad de gracia."
  + "No os proveáis de oro, ni plata, ni cobre en vuestros cintos; ni de alforja para el camino, ni de dos túnicas, ni de calzado, ni de bordón; porque el obrero es digno de su alimento."
    - "Y si la casa fuere digna, vuestra paz vendrá sobre ella; mas si no fuere digna, vuestra paz se volverá a vosotros. Y si alguno no os recibiere, ni oyere vuestras palabras, salid de aquella casa o ciudad, y sacudid el polvo de vuestros pies."
- "He aquí, yo os envío como a ovejas en medio de lobos; sed, pues, prudentes como serpientes, y sencillos como palomas."
- "Y no temáis a los que matan el cuerpo, mas el alma no pueden matar; temed más bien a aquel que puede destruir el alma y el cuerpo en el infierno."
  + "Y a cualquiera que me niegue delante de los hombres, yo también le negaré delante de mi Padre que está en los cielos."
- Jesús, causa de división
  + "No penséis que he venido para traer paz a la tierra; no he venido para traer paz, sino espada."
  + "El que halla su vida, la perderá; y el que pierde su vida por causa de mí, la hallará."

*** Cap. 11
- Mensaje a Juan el Bautista
  + se cura todos los malos a los enfermos, "y a los pobres es anunciado el evangelio"?
  + que relevenacia tenia Juan el Bautista, previo la aparición de Jesús?? (profeta? mensajero?)
    - sobre las criticas hacia el (estaba en la carcel?)
- a pesar que ciertas ciudades presenciaron los milagros de Jesús no se 'arrepintieron de sus pecandos'
  + se menciona que seran castigadas mas que Sodoma porque ahi reinaba al menos la ignorancia/maldad para justificar sus actos
- "Te alabo, Padre, Señor del cielo y de la tierra, porque escondiste estas cosas de los sabios y de los entendidos, y las revelaste a los niños."??
  + "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar. Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón; y hallaréis descanso para vuestras almas; porque mi yugo es fácil, y ligera mi carga." (cual era su carga?)

*** Cap. 12
- "hacen lo que no es lícito hacer en el día(s) de reposo"?? (ayunas?)
  + usar la logica sobre necesidades basicas
    - es lícito hacer el bien
- Por qué se menciona que pasara desapercibido y Jesús sera discreto? en cuanto a su labor/estatus?
- "Todo reino dividido contra sí mismo, es asolado, y toda ciudad o casa dividida contra sí misma, no permanecerá.
  + "El que no es conmigo, contra mí es; y el que conmigo no recoge, desparrama."
  + "Todo pecado y blasfemia será perdonado a los hombres; mas la blasfemia contra el Espíritu no les será perdonada."
  + "O haced el árbol bueno, y su fruto bueno, o haced el árbol malo, y su fruto malo; porque por el fruto se conoce el árbol"
    - "¿Cómo podéis hablar lo bueno, siendo malos? Porque de la abundancia del corazón habla la boca."
- "La generación perversa demanda señal" (algun indicativo que pruebe divino sendero? poder?)
- "El espíritu inmundo que vuelve"

*** Cap. 13
- Jesús hablabla a las personas (fuera de su circulo) que se reunian a escuharlo solo en *Párabolas*
  + a sus dicipulos dijo, que se les concedio el entendimiento del misterio del reino de los cielos
  + el resto de personas no tenian ese entendimiento
    - "porque viendo no ven, y oyendo no oyen, ni entienden"
    - De manera que se cumple en ellos la profecía de Isaías, que dijo:
      "De oído oiréis, y no entenderéis;
      Y viendo veréis, y no percibiréis.
      Porque el corazón de este pueblo se ha engrosado,
      Y con los oídos oyen pesadamente,
      Y han cerrado sus ojos;
      Para que no vean con los ojos,
      Y oigan con los oídos,
      Y con el corazón entiendan,
      Y se conviertan,
      Y yo los sane."
- Parábolas referidas:
  + P. del sembrador
  + P. del trigo y la cizaña
  + P. de la semilla de mostaza
  + P. de la levadura
  + P. del tesoro escondido
  + P. de la perla de gran precio
  + P. de la red
- "Abriré en parábolas mi boca;
  Declararé cosas escondidas desde la fundación del mundo."
  + RELEER las parábolas para entender mejor

*** Cap. 14
- Matan a Juan el Bautista
- Jesús realiza el milagro de multiplicar la comida para 5000 y mas personas
- Jesús realiza el milagro de caminar sobre el agua

*** Cap. 15
- "Este pueblo de labios me honra;
  Mas su corazón está lejos de mí.
  Pues en vano me honran,
  Enseñando como doctrinas, mandamientos de hombres."
- Parábola: "son ciegos guías de ciegos; y si el ciego guiare al ciego, ambos caerán en el hoyo."
  + Habla acerca del veneno que puede salir de la boca para hacer perder el camino de la gente, incluso cometer pecados (malos pensamientos, los homicidios, los adulterios, las fornicaciones, los hurtos, los falsos testimonios, las blasfemias, etc).
- RELEER La fe de la mujer cananea

*** Cap. 16
- La demanda de una señal??
  + "La generación mala y adúltera demanda señal; pero señal no le será dada, sino la señal del profeta Jonás."
- Jesús habla sobre cuidarse de "la doctrina de los fariseos y de los saduceos."
- Jesús habla sobre edificar su iglesia y de darles las llaves de las puertas del cielo a Pedro.
- Jesús anuncia su muerte, y les dice a sus dicipulos:
  "Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame. Porque todo el que quiera salvar su vida, la perderá; y todo el que pierda su vida por causa de mí, la hallará. Porque ¿qué aprovechará al hombre, si ganare todo el mundo, y perdiere su alma? ¿O qué recompensa dará el hombre por su alma?"

*** Cap. 17
- Jesús hablo en un monte con Moises y Elias (era Juan el bautista? un profeta que mataron sin saber)
  + les pidio a sus discipulos que no hablen de los visto hasta su resurreccion.
- Con fe nada sera imposible? (se necesita oracion y ayuno)

*** Cap. 18
- ¿Quien es el mayor en el reino de los cielos?
  + hace su comparacion con un niño (inocencia?) vs sus discipulos
- Habla que es preferible perder un ojo, mano o pie, que estar completo, si estos te llevan a cometer pecados.
- Parábola de la oveja perdida
- "... si tu hermano peca contra ti, ve y repréndele estando tú y él solos; si te oyere, has ganado a tu hermano."
  + "... todo lo que atéis en la tierra, será atado en el cielo; y todo lo que desatéis en la tierra, será desatado en el cielo."
- historia sobre el señor y la deuda del siervo y el consiervo (siervo del siervo)
  + "... perdonáis de todo corazón cada uno a su hermano sus ofensas"

*** Cap. 19
- Jesús habla sobre el divorcio:
  "Por esto el hombre dejará padre y madre, y se unirá a su mujer, y los dos serán una sola carne?
  Así que no son ya más dos, sino una sola carne; por tanto, lo que Dios juntó, no lo separe el hombre."
  + "... cualquiera que repudia a su mujer, salvo por causa de fornicación, y se casa con otra, adultera; y el que se casa con la repudiada, adultera."
  + "No todos son capaces de recibir esto" (matrimonio?)...  "sino aquellos a quienes es dado." ... "El que sea capaz de recibir esto, que lo reciba."
- De los niños es el reino de los cielos (por su inocencia?)
- Para entrar al reino de los cielos, llevar a cabo los mandamientos:
  No matarás.
  No adulterarás.
  No hurtarás.
  No dirás falso testimonio.
  Honra a tu padre y a tu madre.
  Amarás a tu prójimo como a ti mismo.
  + "es más fácil pasar un camello por el ojo de una aguja, que entrar un rico en el reino de Dios"

*** Cap. 20
- Los obreros de la viña (comparación con el reino de los cielos)
  + se conviene pagar/recompensar de cierta forma y a las personas aceptar o no
- Jesús anuncia su muerte por 3ra vez.
- "Sabéis que los gobernantes de las naciones se enseñorean de ellas, y los que son grandes ejercen sobre ellas potestad. Mas entre vosotros no será así, sino que el que quiera hacerse grande entre vosotros será vuestro servidor, y el que quiera ser el primero entre vosotros será vuestro siervo; como el Hijo del Hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos."

*** Cap. 21
- Jesús sabia que le deparaba el futuro, es adelantaba a los acontecimientos.
- Como fuente de sus milagros, revelaba "Y todo lo que pidiereis en oración, creyendo, lo recibiréis."
- Parábola de los dos hijos
  + Análisis sobre hacer las cosas, de mala manera y no hacerlas en absoluto?
- Parábola Los labradores malvados
  + "La piedra que desecharon los edificadores,
    Ha venido a ser cabeza del ángulo."
    "... Por tanto os digo, que el reino de Dios será quitado de vosotros,
    y será dado a gente que produzca los frutos de él."

*** Cap. 22
- Parábola de la fiesta de bodas
  + "Las bodas a la verdad están preparadas; mas los que fueron convidados no eran dignos."
- De Jesús era dicho que era amante de la verdad, y que enseñaba con la verdad el camino de Dios. Y con eso trataba a todos, ya que no juzgaba por la apariencia (alcurnia) de los hombres.
- "... en la resurrección ni se casarán ni se darán en casamiento, sino serán como los ángeles de Dios en el cielo"
- "Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente. Este es el primero y grande mandamiento. Y el segundo es semejante: Amarás a tu prójimo como a ti mismo. De estos dos mandamientos depende toda la ley y los profetas."
**** ¿De quién es hijo el Cristo?
- RELEER y ANALIZAR este verso.

*** Cap. 23
- "... el que se enaltece será humillado, y el que se humilla será enaltecido."
  + los escribas y fariseos actuaban mal hace un buen tiempo??
  + los llamaba hipócritas, decia que: "cerráis el reino de los cielos delante de los hombres; pues ni entráis vosotros, ni dejáis entrar a los que están entrando."
- "Pues el que jura por el altar, jura por él, y por todo lo que está sobre él; el que jura por el templo, jura por él, y por el que lo habita; y el que jura por el cielo, jura por el trono de Dios, y por aquel que está sentado en él."
  + "¡Guías ciegos, que coláis el mosquito, y tragáis el camello!" ??
  + "¡Serpientes, generación de víboras!"
- Decia "envío profetas y sabios y escribas; y de ellos, a unos mataréis y crucificaréis, y a otros azotaréis en vuestras sinagogas, y perseguiréis de ciudad en ciudad".

*** Cap. 24
- "... y por haberse multiplicado la maldad, el amor de muchos se enfriará. Mas el que persevere hasta el fin, este será salvo."
  + Jesús habla sobre lo que vendra antes del fin, de las guerras y desastres venideros, asi como falsos profetas
  + Se necesita contexto para la frase "... cuando veáis en el lugar santo la abominación desoladora de que habló el profeta Daniel... "
- La venida del Hijo del Hombre
  + "E inmediatamente después de la tribulación de aquellos días, el sol se oscurecerá,
    y la luna no dará su resplandor, y las estrellas caerán del cielo,
    y las potencias de los cielos serán conmovidas.
    Entonces aparecerá la señal del Hijo del Hombre en el cielo;
    y entonces lamentarán todas las tribus de la tierra,
    y verán al Hijo del Hombre viniendo sobre las nubes del cielo, con poder y gran gloria.
    Y enviará sus ángeles con gran voz de trompeta, y juntarán a sus escogidos,
    de los cuatro vientos, desde un extremo del cielo hasta el otro."
- Habla de la Parábola de la higuera, y como todo acontecera en el momento menos esperado.
  + pero que las señales seran el aviso de lo que esta por venir
  + asi mismo tomaran por sorpresa a los que hacen el bien y el mal
    + Referencia al RAPTO!?

*** Cap. 25
- Parábola de las diez vírgenes
- Parábola de los talentos
  + a que se refiere con talentos? es dinero??
- Habla de como se hara un juicio en las naciones, separando los buenos de los malos
  + y quienes ayudaron a los necesitados, como si se Jesús se tratara recibiran la gloria
  + mientras los que hicieron lo contrario, seran castigados

*** Cap. 26
- Habla como aviso a sus discipulos como lo iban a aprehender en la epoca de pascuas y su muerte se acercaba.
  + Menciono que este iba a ser negado por sus discipulos (3 veces por Pedro).
  + Tambien proclamo que iba a ser traicionado por uno de ellos (Judas).
- Tuvo su ultima cena (de pascuas), y más tarde fue a orar.
  + "Velad y orad, para que no entréis en tentación; el espíritu a la verdad está dispuesto, pero la carne es débil."
  + Advirtio que su captura es lo que tiene que pasar e dejo en claro que podia pedir ayuda divina, "¿Pero cómo entonces se cumplirían las Escrituras, de que es necesario que así se haga?"
- Se cumplio su arresto.

*** Cap. 27
- Judas se arrepintio de vender a Jesús y se mato, aun asi no cambio en nada lo que tenia que pasar.
- Se realizo un juicio en donde los viejos, sacedotes y escribas estaban confabulados.
  + Poncio Pilato como governador dirigio el juicio, pero al final fue el pueblo quien convencido decidio su muerte.
  + "Y respondiendo todo el pueblo, dijo: Su sangre sea sobre nosotros, y sobre nuestros hijos."
- Se cuenta la crucificción y muerte de Jesús.
  + Durante este tiempo sucedieron cosas que se pueden describir como *misticas*.
- Despues de su muerte, se dijo que recusitará en 3 dias.

*** Cap. 28 (por leer Cap. 29)
- Jesús resucito, y un angel fue a anunciar (a las Marias) en el lugar de su sepulcro del milagro.
  + Aviso que se encontraria con sus dicipulos en Galilea.
  + Hay un comentario que dice que los guardias avisaron de los sucedido (a los ancianos y sacerdotes)
    - pero fueron sobornados para decir que los dicipulos se llevaron el cuerpo en la noche (señalando que los judíos creen eso hasya el día de hoy).
- En el monte del encuentro Jesús les dijo:
  "Toda potestad me es dada en el cielo y en la tierra.
  Por tanto, id, y haced discípulos a todas las naciones,
  bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo;
  enseñándoles que guarden todas las cosas que os he mandado;
  y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo.
  Amén."


** Evangelio S. Marcos

*** Cap. 1
- Se remarca desde la intro (la afirmación) sobre el titulo de Jesús, como hijo de Dios.
- "Como está escrito en Isaías el profeta:
He aquí yo envío mi mensajero delante de tu faz,
El cual preparará tu camino delante de ti.
Voz del que clama en el desierto:
Preparad el camino del Señor;
Enderezad sus sendas."
- Hay un resumen del bautizo, de como conseguia dicipulos y curaba enfermos.
  + Visto desde una perspectiva diferente, agregando cosas a la historia.

*** Cap. 2
- Se recapitula como Jesús curo a un paralitico.
  + queda la duda, tantas personas se acercaban a el para que los cure que ya no alcanzaban en su casa
  + en el caso del paralitico sus amigos/familiares treparon el techo
    - si fue igual su fe, acaso se reunieron asi cuando lo acusaron y crucificaron? o solo fue por interes??
- Los publicanos y pecadores (a quien se refiere? rameras, asesinos?) eran mal visto incluso por los judíos??
- Analizar mejor *la pregunta sobre el ayuno*
- La necesidad vence a la costumbre religiosa, sobre *el dia del reposo*.

*** Cap. 3
- La historia de *el hombre de la mano seca* es una buena reflexión sobre el bien y el mal, sobre la tradición.
  + "¿Es lícito en los días de reposo hacer bien,
    o hacer mal; salvar la vida, o quitarla?
    Pero ellos callaban.
    Entonces, mirándolos alrededor con enojo,
    entristecido por la dureza de sus corazones"
    - los fariseos y herodianos mostraban soberbia, querian probar los /milagros/ que Jesús podia realizar
    - no les importaba si lo hacia o no, sino el hecha de que ponia a prueba su juicio y creencias
- Trataban de acusar la fuente de sus milagros calumniando el /Espíritu Santo/
  + les respondia en parábolas "¿Cómo puede Satanás echar fuera a Satanás?"
- "... todo aquel que hace la voluntad de Dios,
  ese es mi hermano, y mi hermana, y mi madre."

*** Cap. 4
- Con las parábolas posiblemente se queria evitar que solo vinieran creyentes dudoso.
  + siempre y cuando ganen el paraiso prometido, diran o apoyaran lo que sea
  + "... para que no se conviertan, y les sean perdonados los pecados."
- Parábolas referidas:
  + P. del sembrador
    - El sembrador es el que siembra la palabra.
    Las semillas que caen en distintos lugares,
    es en quienes se siembra la palabra.
    - Hay quienes pierden la palabra por Satanás,
      los que en momentos que se ponen a prueba la dejan
      los que se ven influenciados por el medio y la dejan
      y finalmente los que la reciben y rinde frutos.
  + No hay nada oculto que no haya de ser manifestado;
    ni escondido, que no haya de salir a luz.
  + Habia algunas comparaciones a semillas con el Reino de Dios.

*** Cap. 5
- Las personas que actuaban sin cordura (hablando solos, lastimandose, etc) eran considerados poseidos por demonios.
  + A los que Jesús podía sacar sin el menor problema.
- Tenia el poder de sanar e incluso revivir a los muertos.

*** Cap. 6
- Es un poco confuso la explicación de la muerte de Juan el Bautista, comparada a la anterior.
  + parece que el rey Herodes habla que lo revivieron (debido a los milagros que los dicipulos de Jesús podían hacer)
  + pero después se menciona la historia de como lo decapitaron
- Jesús realizó el milagro de multiplicar los panes y pescados
  + al realizar posteriormente el milágro de caminar sobre el mar asustó a sus discipulos
  + dice que se debió a que "estában endurecidos sus corazónes"

*** Cap. 7
- Al criticar los escribas y fariseos el que los discipulos de Jesús no se lavaron las manos para comer.
  + les respondia llamandolos hipócritas, citando a Isaías:
    "Este pueblo de labios me honra,
     Mas su corazón está lejos de mí.
     Pues en vano me honran,
     Enseñando como doctrinas mandamientos de hombres."
  + Refiriendose a que ellos tambien invalidaban mandamientos al anteponer sus tradiciones primero.
  + a la multitud que estába presente les hablo al respecto en forma de parábola:
    "Nada hay fuera del hombre que entre en él,
     que le pueda contaminar; pero lo que sale de él,
     eso es lo que contamina al hombre."
    - habla de lo que se ingiere y termina en la letrina
    - explicando que en cambio al salir del corazón salen
      "los malos pensamientos, los adulterios, las fornicaciones, los homicidios,
       los hurtos, las avaricias, las maldades, el engaño, la lascivia, la envidia,
       la maledicencia, la soberbia, la insensatez."

*** Cap. 8
- "¿No entendéis ni comprendéis? ¿Aún tenéis endurecido vuestro corazón? ¿Teniendo ojos no veis, y teniendo oídos no oís?"

*** Cap. 9
- "Si alguno quiere ser el primero (discipulo en importancia de Jesús), será el postrero de todos, y el servidor de todos."
  + "Y tomó a un niño, y lo puso en medio de ellos; y tomándole en sus brazos, les dijo:
    El que reciba en mi nombre a un niño como este, me recibe a mí; y el que a mí me recibe, no me recibe a mí sino al que me envió."
- "Si tu mano te fuere ocasión de caer, córtala; mejor te es entrar en la vida manco, que teniendo dos manos ir al infierno ...
  Y si tu pie te fuere ocasión de caer, córtalo; mejor te es entrar a la vida cojo, que teniendo dos pies ser echado en el infierno ...
  Y si tu ojo te fuere ocasión de caer, sácalo; mejor te es entrar en el reino de Dios con un ojo, que teniendo dos ojos ser echado al infierno, donde el gusano de ellos no muere, y el fuego nunca se apaga."

*** Cap. 10
- Jesús habla sobre el divorcio:
  + dice que debido a la *dureza de corazón* de las personas se escribrio ese mandmiento
  + "... al principio de la creación, varón y hembra los hizo Dios.
    Por esto dejará el hombre a su padre y a su madre, y se unirá a su mujer,
    y los dos serán una sola carne; así que no son ya más dos, sino uno.
    Por tanto, lo que Dios juntó, no lo separe el hombre."
    - que aque el que repudia a su pareja, para casarse con otra persona comete adulterio
- "el que no reciba el reino de Dios como un niño, no entrará en él."
- Jesús menciona como es dificil a los ricos entrar en el reino de los cielos
  + estan muy atados a sus posesiones materiales
- "... el Hijo del Hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos."

*** Cap. 11
- "... todo lo que pidiereis orando, creed que lo recibiréis, y os vendrá.
  Y cuando estéis orando, perdonad, si tenéis algo contra alguno,
  para que también vuestro Padre que está en los cielos os perdone a vosotros vuestras ofensas.
  Porque si vosotros no perdonáis, tampoco vuestro Padre que está en los cielos os perdonará vuestras ofensas."

*** Cap. 12
- Cuando no sepas si algo es correcto, recuerda que puedes errar al actuar por *ignorar las escrituras y el poder de Dios*.
  + "... que uno es Dios, y no hay otro fuera de él y el amarle con todo el corazón,
    con todo el entendimiento, con toda el alma, y con todas las fuerzas,
    y amar al prójimo como a uno mismo, es más que todos los holocaustos y sacrificios."

*** Cap. 13
- Jesús habla de las señales del fin, y aconseja:
  "Mirad, velad y orad; porque no sabéis cuándo será el tiempo."

*** Cap. 14
- Nos da otra perspectiva de la última cena.
- "Velad y orad, para que no entréis en tentación; el espíritu a la verdad está dispuesto, pero la carne es débil."

*** Cap. 15
- Recapitula lo visto en Mateo sobre la aprensión y muerte de Jesús, desde otra perspectiva.

*** Cap. 16
- Recapitula lo visto en Mateo sobre la resurrección y asención al cielo de Jesús, desde otra perspectiva.


** Evangelio S. Lucas

*** Cap. 1
- En el intro se señala que Lucas no fue contemporaneo de Jesús, pero escribio sobre el.
  + que a pesar de redactar como historiador, y lucir como bibliografia, se busco hacerlo envagelio.
  + se vuelve a recalcar el mensaje que queria transmitir el autor, sobre Jesús como *hijo de Dios*.
- Recapitula con más detalle el nacimiento de *Juan el Bautista* y de *Jesús*.
  + en ambos casos fue enviado el angel Gabriel, primero para anunciar la concepción de Juan
  + 6 meses después fue enviado para avisar a maria sobre su destino y la concepción de Jesús
    - *BUSCAR* la comparación de este envento en otros libros religiosos, sobre ser llamado el _Hijo del Altísimo_ o _Hijo de Dios_
    - *BUSCAR* la comparación de este envento en otros libros religiosos, a que consideran _Espíritu Santo_
  + el dialogo de Maria sobre Dios es interesante para *RELEER*

*** Cap. 2
- Se relata el nacimiento de Jesús, sobre un censo, viajes y pastores que fueron avisados por un angel sobre este evento.
- Tambien se habla de su presentación en el templo, de su crecimiento y su comportamiento temprano.
  + se maravillaban de su inteligencia y respuestas para su corta edad

*** Cap. 3
- Juan predicaba el *bautismo del arrepentimiento* para el perdón de los pecados.
  + se hace referencia a las palabras del profeta Isaías:
    "Preparad el camino del Señor;
    Enderezad sus sendas.
    Todo valle se rellenará,
    Y se bajará todo monte y collado;
    Los caminos torcidos serán enderezados,
    Y los caminos ásperos allanados;
    Y verá toda carne la salvación de Dios."
- Decía a las multitudes:
  "¡Oh generación de víboras! ¿Quién os enseñó a huir de la ira venidera?
  *Haced, pues, frutos dignos de arrepentimiento*,
  y no comencéis a decir dentro de vosotros mismos:
  Tenemos a Abraham por padre;
  porque os digo que Dios puede levantar hijos a Abraham aun de estas piedras.
  Y ya también el hacha está puesta a la raíz de los árboles; por tanto,
  *todo árbol que no da buen fruto se corta y se echa en el fuego*."
- Enseñaba a la personas:
  + si se tiene más (vestimenta, comida, etc), dar al que no tiene/necesita
  + si tienen oficio/poder ser honestos y no abusar de ello
- Menciona que mientras el bautizaba en agua, vendrá alguien más poderoso que el (refiriendose a Jesús)
  + quien los bautizará en Espíritu Santo y fuego
  + este salvara a los justos y enviara al tormento a los pecadores
- Mientras lleva a cavo el bautismo de Jesús, se menciona que "orando, el cielo se abrió,
  y descendió el Espíritu Santo sobre él en forma corporal, como paloma,
  y vino una voz del cielo que decía:
  Tú eres mi Hijo amado; en ti tengo complacencia."

*** Cap. 4
- Cuando Jesús fue a Nazaret y leyo en una sinagoga el libro del profeta Isaías, reflexiono en sus palabras.
  + comparo que hizo varias de las cosas que mencionaba
  + al mencionar que otros antes que el no fueron aceptados en sus lugares de origen
    - y que de igual manera no pudieron desempeñar milagros de la misma forma
    - provoco la ira de los presentes, quienes lo sacáron de ahi
- Jesús recorrio Galilea predicando, decia:
  "Es necesario que también a otras ciudades anuncie el evangelio del reino de Dios;
  porque para esto he sido enviado."

*** Cap. 5
- Jesús tambien se reuinía con pecadores pasando tiempo con ellos, y cuando preguntaban porque decia:
  "Los que están sanos no tienen necesidad de médico, sino los enfermos.
  No he venido a llamar a justos, sino a pecadores al arrepentimiento."

*** Cap. 6
- Cuando le preguntaron en una ocasión, porque sus discipulos comían en día de reposo:
  "¿Ni aun esto habéis leído, lo que hizo David cuando tuvo hambre él, y los que con él estaban;
  cómo entró en la casa de Dios, y tomó los panes de la proposición,
  de los cuales no es lícito comer sino solo a los sacerdotes,
  y comió, y dio también a los que estaban con él?"
- Les decia a sus discípulos:
  "Bienaventurados vosotros los pobres, porque vuestro es el reino de Dios.
  Bienaventurados los que ahora tenéis hambre, porque seréis saciados.
  Bienaventurados los que ahora lloráis, porque reiréis.
  Bienaventurados seréis cuando los hombres os aborrezcan, y cuando os aparten de sí,
  y os vituperen, y desechen vuestro nombre como malo, por causa del Hijo del Hombre.
  Gozaos en aquel día, y alegraos, porque he aquí vuestro galardón es grande en los cielos;
  porque así hacían sus padres con los profetas.
  Mas ¡ay de vosotros, ricos! porque ya tenéis vuestro consuelo.
  ¡Ay de vosotros, los que ahora estáis saciados! porque tendréis hambre.
  ¡Ay de vosotros, los que ahora reís! porque lamentaréis y lloraréis.
  ¡Ay de vosotros, cuando todos los hombres hablen bien de vosotros!
  porque así hacían sus padres con los falsos profetas."
- Tambien les dijo:
  "Amad a vuestros enemigos, haced bien a los que os aborrecen;
  bendecid a los que os maldicen, y orad por los que os calumnian.
  Al que te hiera en una mejilla, preséntale también la otra;
  y al que te quite la capa, ni aun la túnica le niegues.
  A cualquiera que te pida, dale; y al que tome lo que es tuyo,
  no pidas que te lo devuelva.
  Y como queréis que hagan los hombres con vosotros,
  así también haced vosotros con ellos.
  Porque si amáis a los que os aman, ¿qué mérito tenéis? ...
  ... Amad, pues, a vuestros enemigos, y haced bien, y prestad,
  no esperando de ello nada; y será vuestro galardón grande,
  y seréis hijos del Altísimo;
  porque él es benigno para con los ingratos y malos.
  Sed, pues, misericordiosos,
  como también vuestro Padre es misericordioso."
- De igual manera:
  "*No juzguéis, y no seréis juzgados*;
  no condenéis, y no seréis condenados;
  perdonad, y seréis perdonados.
  Dad, y se os dará; medida buena, apretada,
  remecida y rebosando darán en vuestro regazo;
  porque con la misma medida con que medís,
  os volverán a medir."
- Sobre el reflejo de las acciones:
  "... *cada árbol se conoce por su fruto*;
  pues no se cosechan higos de los espinos,
  ni de las zarzas se vendimian uvas.
  El hombre bueno, del buen tesoro de su corazón saca lo bueno;
  y el hombre malo, del mal tesoro de su corazón saca lo malo;
  porque *de la abundancia del corazón habla la boca*."
- La reflexión sobre "los dos cimientos" es una buena analogía sobre saber o no,
  escuchar consejos.

*** Cap. 7
- Existian los discipulos de Juan el Bautista y de Jesús.
  + Juan no sabia de Jesús mas que por historias de otros
  + mando a preguntar a dos de sus discipulos, si *el era el enviado (de Dios) o si iba a venir otro más?*
  + Jesús demostro quien era por sus milagros (acciones), mas que por sus palabras
- Jesús conocia de Juan el Bautista, y lo referia como un profeta:
  "He aquí, envío mi mensajero delante de tu faz,
  El cual preparará tu camino delante de ti."
  + ubieron quienes se bautizaron con él y ubieron quienes eligieron no hacerlo
  + Jesús menciono que sin importar quien viene pata predicar la palabra,
    hay personas que todo lo juzgan (sea recatado o no)
    y negaran la verdad aunque este presente frente a ellos
- Jesús fue invitado a la casa de un fariseo (de los no creyentes)
  + una mujer pecadora (prostituta) hecho lagrimas sobre sus pies y las limpio con sus cabellos,
  ademas de besarlos y ungirlos en perfume
  + se comparo con una parábola sobre dos deudóres y el perdon de sus deudas, y se pregunto ¿quien estaria más agradecido?
    - una buena alegoria sobre el arrepentimiento y el perdón de los pecados

*** Cap. 8
- Se menciona que aparte de los 12 discipulos, habían mujeres que habían sido sanadas que seguían a Jesús.
  + por ejemplo María Magdalena
- Habla sobre lo que las personas "ocultan" y cómo al final, todo sale a la luz.
  + asi mismo como el bien se premiara (dándole), el mal se castigará (quitándole).
- Jesús consideraba su familia, no solo por la sangre sino a quien *oye la palabra de Dios y la aplica*.
- Jesús al calmar una tempestad en el lago solo con sus palabras, a sus discipulos sorprendidos les pregunto:
  "¿Dónde está vuestra fe?", al no creer que algo asi era posible o que podia hacerse.
  + una buena reflexión sobre *creer* en el poder de Dios y a quienes da su gracia.

*** Cap. 9
- Jesús dijo a sus discipulos:
  "Porque todo el que quiera salvar su vida, la perderá;
  y todo el que pierda su vida por causa de mí, este la salvará.
  Pues *¿qué aprovecha al hombre, si gana todo el mundo,*
  *y se destruye o se pierde a sí mismo?*
  Porque el que se avergonzare de mí y de mis palabras,
  de este se avergonzará el Hijo del Hombre cuando venga en su gloria,
  y en la del Padre, y de los santos ángeles."
  + reflexión interesante sobre el camino a escoger,
    sobre la salvación vs un amor vano.
- Cuando no fue recibido en una aldea, sus discipulos sugirieron su destrucción, más el respondio:
  "... el Hijo del Hombre no ha venido para perder las almas de los hombres, sino para salvarlas."

*** Cap. 10
- Hablando de la palabra que difundian sus discipulos:
  "El que a vosotros oye, a mí me oye; y el que a vosotros desecha,
  a mí me desecha; y el que me desecha a mí, desecha al que me envió."
- Les recordaba a sus discipulos que más que estar felices por sacar demonios (tener ese poder)
  + deben estar felices porque por sus acciones iran al cielo
- Una buena referencia sobre *amar al prójimo como a ti mismo*
  + da un ejemplo con la historia del buen samaritano

*** Cap. 11
- Jesús les enseña a sus discipulos a orar, diciendo:
  "Padre nuestro que estás en los cielos, santificado sea tu nombre.
  Venga tu reino. Hágase tu voluntad, como en el cielo, así también en la tierra.
  El pan nuestro de cada día, dánoslo hoy.
  Y perdónanos nuestros pecados, porque también nosotros perdonamos a todos los que nos deben.
  Y no nos metas en tentación, mas líbranos del mal."
- Hablando de Dios les dijo:
  "Pedid, y se os dará;
  buscad, y hallaréis;
  llamad, y se os abrirá.
  Porque todo aquel que pide, recibe;
  y el que busca, halla;
  y al que llama, se le abrirá."
- Sobre la posición que se encuentran muchos:
  "El que no es conmigo, contra mí es; y el que conmigo no recoge, desparrama."
  + "... bienaventurados los que oyen la palabra de Dios, y la guardan."
- Hay un referencia al profeta (¿?) Jonas aqui y Ninive (buscar referencia).
- Aqui se mencion tambien como "La lámpara del cuerpo es el ojo"
  + si el ojo es bueno el cuerpo está lleno de luz
  + si el ojo es maligo el cuerpo está en tinieblas
    - posible referencia a como el *ojo es ventana del corazón* y muestra tu ser.

*** Cap. 12
- Una reflexión sobre "La levadura de los fariseos" y como hay que cuidarse de la hipocresía.
  + tanto ser victima de gente hipocrita, como perpetrarla uno
  + siendo algo que aparenta ser bueno (a los sentidos), en palabras o acciones
  + pero en realidad es todo lo contrario
    - aunque se oculte este comportamiento ahora, en el juicio todo se sabrá
- Que hay que temer más que a los que matan el cuerpo, al que quita la vida y condena al infierno.
  + se refiere a Dios y su poder
  + una referencia con pajaros o la cantidad de cabello que uno tiene
    - como Dios lo sabe todo, y *es a él a quien rendiremos cuentas*
- Mientras la confesión puede ser de ti hacia Jesús, Jesús confesara delante de Dios.
  + aunque puede excusarse palabras contra Jesús, no sera el caso cuando sean palabras contra Dios
- Jesús hizo una buena reflexión sobre la herencia de unos hermanos:
  "Mirad, y guardaos de toda avaricia;
  porque *la vida del hombre no consiste en la abundancia de los bienes que posee.*"
  + un hombre puede ser rico en la tierra, pero no en igual medida a los ojos de Dios
- Les dijo a sus discipulos:
  "No os afanéis por vuestra vida, qué comeréis;
  ni por el cuerpo, qué vestiréis.
  La vida es más que la comida,
  y el cuerpo que el vestido."
  + dar una jerarquía de importancia a las cosas en la vida
    - no perder la compostura/caracter por cosas que no valen la pena
  + analizar la reflexión sobre los lirios y Salomón
    - buscar las cosas de necesidad primero en el Reino de Dios (y lo demás se los dará como añadidúra)
- Analizar la reflexión sobre el ciervo vigilante.

*** Cap. 13
- Jesús menciona, que tanto los que pecan más o menos, sino se arrepienten antes no se salvaran.
- Primero es necesario abonar la mente (la palabra), para luego recoger la cosechar.
- No se trata de "conocer" solamente, o de relacionarse con personas que hacen el bien.
  + tienes que llevarlo a cabo, ser participe en el cambio
  + es la única manera de pasar por las puertas del cielo
- *IMPORTANTE*: Jesús se refiere a el como un profeta en "Lamento de Jesús sobre Jerusalén".

*** Cap. 14
- Jesús enseña sobre humildad en la parábola de "Los convidados a las bodas".
  + no buscando mostrar su importancia frente a otros:
    "... cualquiera que se enaltece, será humillado;
    y el que se humilla, será enaltecido."
  + igualmente recomienda cuando se hace un banquete, al fin de invitar a seres queridos o personas pudientes, invitar a los necesitados.
    - ya que los primeros te pueden recompensar, mas los segundos no.
    - la recompensa es en el reino de los cielos.
- En la parábola de "La gran cena" parece hacer referencia a cuando se prepara algo bueno para la gente pero esta lo rechaza.
  + ya sea por ocupaciones, distracciones o situaciones terrenales que merman el buen juicio
  + sera bienvenido a la salvación cualquiera que la acepte, empezando por los más humildes
- Un dialogo de *Lo que cuesta seguir a Cristo* cuando incluso las personas cercanas a ti se oponen.
  - hay que tomar en cuenta los sacrificios y la meta final

*** Cap. 15
- Se habla sobre el gozo de salvar a 1 pecador que se arrepiente,
  sobre 99 personas que no necesitan arrepentirse.
  + compara cuando se pierde una moneda y uno se esfuerza en encontrarla.
  + el ejemplo de 2 hermanos, mientras el menor fue por el mal camino y se arrepintio, el mayor nunca peco.
    - sin embargo se ayudo y celebro al segundo
    - porque ya se lo consideraba muerto, y ahora había recusitado

*** Cap. 16
- Una interesante historia de como un mayordomo al ser descubierto malgastando los bienes de su amo
  + antes de ser despedido trato de hacer un jugarreta con los deudores de este
    - al no verse de capaz de hacer otros trabajos fisicos, incluso mendigar
  + rebajando su deuda y cobrandoles menos para beneficiarles
    - queriendo quedar bien con ellos para que alguno lo contrate posteriormente
  + se advierte que si no paga en esta vida, pagara en la siguiente
    - recalca la "fidelidad" que este tuvo para quien le tendio la mano
    - de como su comportamiento de fidelidad o infidelidad se puede reflejar cuando se tiene mucho o poco
    - ademas *¿si trato asi a su anterior amo, quien dice que no hará lo mismo con el siguiente?*
  + "Ningún siervo puede servir a dos señores; porque o aborrecerá al uno y amará al otro ... No podéis servir a Dios y a las riquezas."
    - de nada sirve justificar la avaricia delante de los demás (o de uno mismo)
    - ya que Dios al conocer nuestros corazónes, puede ver la verdad de algo que tildamos de sublime (siendo todo lo contrario).
- Tambien se hace una referencia al Antiguo Testamento:
  "La ley y los profetas eran hasta Juan;
  desde entonces el reino de Dios es anunciado,
  y todos se esfuerzan por entrar en él."
- Se habla del divorcio y como casarse despues de repudiar a una mujer, o casarse con esta es "adulterio".
  + la palabra *repudio* toma una connotación grande aqui, y merece ser revisa.
- Otra historia tratáda es la de un hombre rico y Lazaro, y sus destinos finales en la otra vida.

*** Cap. 17
- "Dijo Jesús a sus discípulos: Imposible es que no vengan tropiezos; mas ¡ay de aquel por quien vienen!"
  + reflexión sobre los *obstáculos* que uno encuentra en la vida
  + especial enfasis a la persona por la que vienen
    - posiblemente por su actuar, ya fuere bueno y peor aun si fuera malo
  + comenta tambien el mal destino de quien provocase un obstáculo a alguien bueno
  + se habla también del *perdón*:
    "Si tu hermano pecare contra ti, repréndele; y si se arrepintiere, perdónale.
    Y si siete veces al día pecare contra ti, y siete veces al día volviere a ti,
    diciendo: Me arrepiento; perdónale."
- Muesta que la cantidad de *fe* necesaria para hacer grandes cosas, es de un tamaño ínfimo.
  + aun asi, es importante que este ahi
- Con una metáfora sobre "El *deber* del siervo" trata
  + de como es nuestro deber ante el Señor es hacer las cosas que se nos ha asignado
  + sin esperar algun tipo de reconocimiento, más porque es nuestra obligación
    - después vendra la recompensa
  + no hay necesidad de regodiarse, "hicimos lo que _debíamos hacer_"
- En la historia sobre "Diez leprosos son limpiados" recalca la importancia del agradecimiento
  + cuando se nos concede su gloria, a travez de una petición
  + siempre glorificando a Dios (a gran voz y postrándose)
- Trata el tema del día del juicio, que vendra sin aviso.
  + con el consejo de seguir adelante, al fin de mirar para atras (aferrandose a lo material)
  + se habla sobre el *Rapto*

*** Cap. 18
- Habla como Dios hará justicia a los escogidos (dignos de su reino).
  + deja una pregunta abierta, si cuando vuelva Jesús hallará fe en nuestro mundo?
- Señala sobre quien se enaltece y quien se humilla, funciona inversamente prorporcional.
  + quien se enaltece será humillado, y quien se humilla será enaltecido
  + enaltecerse nucho puede terminar perjudicandonos, se convierte en soberbia

*** Cap. 19
- Se recalca en una historia, que Jesús daba importancia en salvar primero a los pecadores,
  ya que eran ellos quien más lo necesitaban.
- En la parábola de "las diez minas" cuenta como un hombre pudiente dio 10 monedas de alto valor a 10 siervos,
  para que negociaran con estas e hicieran crecer su fortuna.
  Se puede entender que:
  + los que lo hicieron les recompenso grandemente con más riqueza
  + los que no lo hicieron (fueron temerosos u holgazanes) se les quito todo
  + los que estan en su contra, encontron el fin
- En su entrada a Jerusalén, se entristecio al conocer el futuro que le esperaba a la ciudad y su pueblo.
  + *NOTA*: revisar archivo historio sobre este eventro

*** Cap. 20
- La parábola de "los labradores malvados" hace una referencia interesante al mundo que habitamos.
  + siendo este creado por Dios, nosotros (los labradores) somos simplemente ocupantes de paso
  + al prestarnosla para que cultivemos sus frutos, se espera una retribución por nuestra parte
    - posiblemente nuestras buenas acciones hacia este y los demás
  + los siervos enviados hacen referencia a profetas relevantes
    - que no fueron escuchados sino castigados
  + el hijo enviado posiblemente se refiere a Jesús
    - y el destino fatal que le esperaba
  + y el futuro que les esperaba a estos labradores cuando llegue el juicio
    - destruyendo a los pecadores y dandoles las tierras (el reino) a quienes lo merecen
  + sobre la piedra y los edificadores, puede hacer referencia hacia la palabra
    - como piedra base para edificar nuestro futuro
    - puede darnos la guia hacia la salvación
    - o mostrarnos la ruta a la destrucción
    - todo depende de quien se cruce en su verdad
- En "la cuestión del tributo" trata el tema sobre las leyes terrenales.
  + se respetaran refiriendose a sus obligaciones terrenales
  + asi mismo las que sean celestiales de manera correspondiente

*** Cap. 21
- Mientras Jesús predecia lo que iba a suceder en el futuro cercano,
  igualmente predecia que para el fin de los tiempos su generación,
  ni las siguientes sabrian cuando llegaria.
  + es algo que sucedera sin aviso
  + aun asi, habrá señales claras de esto

*** Cap. 22
- El versículo sobre "La grandeza en el servicio" requiere mayor análisis, Jesús señala que:
  + A pesar que hay reyes que se enaltecen por tener autoridad sobre sus dominios, ellos deben hacer lo contrario.
  + Ni por la edad (avanzada o prematura), ni liderazgo... sino por la diligencia en servir a los demás.
  + Porque aunque sus discipulos recibirían un reino (en los cielos?) por estar a su lado,
    el deseaba que su ser se mantuviera humilde.
- Indicaba a sus discipulos que *oren para no entrar en tentación* posiblemente ante eventos (pecados) que pudieran suceder.

*** Cap. 23
- Aunque fue aprendido por falsas calumnias, fueron los ancianos, sacerdotes y escribas judíos de alta alcurnia,
  quien terminaron condenandole.
  + Incluso más que las autoridades Romanas que querian soltarlo, porque no encontraban crimen para sentenciarlo.
  + Hace pensar, si lo que les pasaría en el futuro a los judíos tuviera que ver algo con este incidente?
- Jesús señala durante el proceso de su crucifixión a unas mujeres, que al fin de llorar por el debieran hacerlo por ellas y sus hijos, ya que si eso hacian a alguien inocente, solo era de esperarse el destino que le aguardaba al pueblo.
  + Incluso en sus ultimos momentos clamo que su pueblo fuera perdonado, debido a que cometían ese acto por ignorancia.

*** Cap. 24
- Se recalco que entre los libros de Mateo, Marcos, Lucas, etc hay ciertas variaciones en la descripción de los eventos.
  + la cantidad de mujeres que va al sepulcro de Jesús
  + la cantidad de angeles que se encuentran ahi
  + se relata a mator detalle como Jesús se aparacio a dos de los discipulos


** Evangelio S. Juan

*** Cap. 01
- El evangelio de Juan muestra un enfoque y forma de expresarse diferente a los 3 anteriores.
  + En el "El Verbo hecho carne" se puede apreciar, la reflexión que el evangelista quiere provocar en nosotros.
    "En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios.
    Este era en el principio con Dios. Todas las cosas por él fueron hechas,
    y sin él nada de lo que ha sido hecho, fue hecho. En él estaba la vida,
    y la vida era la luz de los hombres. La luz en las tinieblas resplandece,
    y las tinieblas no prevalecieron contra ella."
    - habla sobre nuestra enlace con Dios
    - vale la pena varias lecturas, para entender la profundidad de sus palabras
  + Se menciona que Juan (el autor, posiblemente hijo de Zebedeo) queria dar testimonio sobre los hecho que acontecieron.
- Menciona las palabras de Juan el bautista:
  "Enderezad el camino del Señor, como dijo el profeta Isaías."
  + menciona como para que fuese conocido por Israel, vino el primero a bautizar con agua


*** Cap. 02
- Jesús saca de un templo a comerciantes que ejercian su oficio ahi, diciendo:
  "Quitad de aquí esto, y no hagáis de la casa de mi Padre casa de mercado."
  + es ahi que sus discípulos recordaron de las escrituras: "El celo de tu casa me consume."
  + posteriormente le dijo a los judios que lo criticaban: "Destruid este templo, y en tres días lo levantaré."
    - se acordaron de esta frase tras su muerte y resurrección
    - que no se referia al templo físico sino al corporeo
- A pesar que muchos hombres creian quien era, no se fiaba ya que conocia lo que había en sus corazónes.


*** Cap. 03
- Relata la historia de Nicodemo, tratando temas nuevos para sus creencias judias.
  + el hecho de renacer (espiritualmente) para poder entrar al reino de los cielos.
  + al no entender el concepto de espiritu se hizo la comparación con el viento.
  + se hace una alegoria a su resurrección futuru, pero aun no se podia entender.
- Se menciona sobre la salvación por el hecho de creer en Jesús y su descendencia/parentesco con el Señor.
  + hay una distinción sobre los creyentes que siguen la luz
  + y los pecadores que siguen la oscuridad
- Tambien se habla que no creer en Jesús y su parentesco con el Señor, sería causa de ira del Señor mismo.


*** Cap. 04
- En la historia de la mujer samaritana y el pozo, hay una alusión al "agua viva".
  + la cual a diferencia del agua normal no provocara sed despues
  + sino que sera de una fuente para *vida eterna*
  + mención a que ahi adoraban desconocido, mientras del lado de Jesús adoraban lo conocido
- Dios es *Espiritu*, y para adorarlo hay que hacerlo en espiritu y verdad
  + Jesús menciona que lo que lo nutria era hacer "la voluntad del que me envió, y que acabe su obra"
- Comparación labrar y cosechar, el fruto para la vida eterna
  + de como Jesús envio a sus discipulos para cosechar algo que no labraron
  + lo hicieron otros, aun asi ahora ellas entraron en sus labores
    - se entiende como las vivencias (de profetas) y escritos del viejo testamento
    - asi como el seguir lo proclamado en el pasado, para tener ese futuro esperado


*** Cap. 04 (por leer Cap. 05)
- Al haber curado a un paralitico en dia de reposo y al mencionar su razón de hacerlo:
  "Mi Padre hasta ahora trabaja, y yo trabajo"
  + provocaba a los maestros y escribas judios querer matarle por herejía
- Habla igualmente de las acciones, enseñanzas y potestas que "tiene el Hijo debido al Padre"
  + dando la potestad al Hijo, deben honrarlo como lo hacen con el Padre
  + "El que no honra al Hijo, no honra al Padre que le envió."
    - "El que oye mi palabra, y cree al que me envió, tiene vida eterna;
      y no vendrá a condenación, mas ha pasado de muerte a vida."
  + "Porque como el Padre tiene vida en sí mismo,
    así también ha dado al Hijo el tener vida en sí mismo;
    y también le dio autoridad de hacer juicio,
    por cuanto es el *Hijo del Hombre*."
    - los resultados de haber creido y seguido a Jesús afectara tanto a los vivos,
      como a los que murieron anteriormente a la hora del juicio
    - en cuanto decidira quien será salvado o quien será condenado en la resurrección
  + de como su juicio (justo) se basa en la voluntad del Padre
    - que dar testimonio sobre uno mismo no es verdadero (porque es subjetivo),
      sino es otro quien lo da, aunque Jesús no recibe testimonio de hombre alguno
    - de igual manera que Juan el Bautista dio su testimonio, el testimonio de Jesús es mayor,
      ya que las obras que su Padre le dio para hacer, son su testimonio (sus acciones y milagros)
    - tambien menciona que su Padre dio testimonio de el en las escrituras,
      sin embargo a los enviados previos no se les creyo
    - "Gloria de los hombres no recibo.
      Mas yo os conozco, que no tenéis amor de Dios en vosotros.
      Yo he venido en nombre de mi Padre, y no me recibís;
      si otro viniere en su propio nombre, a ese recibiréis.
      ¿Cómo podéis vosotros creer, pues recibís gloria los unos de los otros,
      y no buscáis la gloria que viene del Dios único?"


*** Cap. 05 (por leer Cap. 06)
-

** Fuentes

+ [[https://my.bible.com/es/bible/149/MAT.1.RVR1960]]
+ [[https://my.bible.com/es/bible/149/MRK.1.RVR1960]]
+ [[https://my.bible.com/es/bible/149/LUK.1.RVR1960]]
+ [[https://my.bible.com/es/bible/149/JHN.1.RVR1960]]
