#+title:    Essential JS 2 for ASP.NET MVC in Visual Studio
#+author:   h4ss4n
#+date:     2022-06-26 dom

* Using Visual Studio 2019

** Prerequisites

- .Net Framework 4.5 and above
- ASP.NET MVC 5
- Visual Studio 2019

** Steps

- Create ASP.NET MVC web application

- Configure Essential JS 2 in the application
  1. Right-click on the project and select Manage NuGet Packages.

  2. Search and install 'Syncfusion.EJ2.MVC5'.
     - Additionally 'Syncfusion.EJ2.JavaScript' and 'Syncfusion.Licensing' will be installed automatically with the package.

  3. Open ~/Views/Web.config file and add the Syncfusion.EJ2 namesapce reference to the <system.web.webPages.razor> element and Syncfusion.EJ2 assembly reference to <system.web> element.

     #+begin_src html

      <configuration>
     ...
     <system.web.webPages.razor>
         ...
         ...
         <pages pageBaseType="System.Web.Mvc.WebViewPage">
             <namespaces>
                 ...
                 ...
                 <add namespace="Syncfusion.EJ2"/>
             </namespaces>
         </pages>
     </system.web.webPages.razor>
     ...
     <system.web>
         <compilation>
             <assemblies>
                 ...
                 ...
                 <add assembly="Syncfusion.EJ2, Culture=neutral" />
             </assemblies>
         </compilation>
     </system.web>
 </configuration>

     #+end_src

  4. Add the client-side resources through CDN in the <head> element of ~/Views/Shared/_Layout.cshtml layout page.

     #+begin_src html

 <head>
     ...

     <!-- Syncfusion Essential JS 2 Styles -->
     <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

     <!-- Syncfusion Essential JS 2 Scripts -->
     <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
 </head>

     #+end_src

  5. Add the Essential JS 2 Script Manager at the end of <body> element in the ~/Views/Shared/_Layout.cshtml layout page.

     #+begin_src html

 <body>
     ...
     <!-- Syncfusion Essential JS 2 ScriptManager -->
     @Html.EJS().ScriptManager()
 </body>

     #+end_src

  6. Add the Syncfusion Essential JS 2 components in any web page (cshtml) in the ~/Views folder.

     For example, the calendar component is added to the ~/Views/Home/Index.cshtml page.

     #+begin_src html

 <div>
     @Html.EJS().Calendar("calendar").Render()
 </div>

     #+end_src

     Don't run the application until the lincese key is added to the project.

- Generate the License Key

  1. License keys can be generated from the License & Downloads section of the Syncfusion website: [[https://www.syncfusion.com/account/downloads]]

     In the Bottom of the page click the link 'Get License Key' and a window will pop up, fill the *Platform:* ASP.NET MVC and *Version:* <Syncfusion.EJ2.MVC5 current package's version>

     Copy the 'License Key' content for later.

  2. Register the license key in Application_Start method of Global.asax.cs

     #+begin_src csharp

protected void Application_Start(object sender, EventArgs e)
        {
            //Register Syncfusion License
            Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("<paste license key here>");

            // Default code that runs on application startup
            ...
            ...
       }

     #+end_src

- Avoid compile-time and run-time errors
  1. Install 'Microsoft.TypeScript.MSBuild' NuGet package

  2. Right-click the project node and choose Add > New Item. Choose the 'TypeScript JSON Configuration File', and then click Add

     Visual Studio adds the 'tsconfig.json' file to the project root.

  3. Open the file and update to set the compiler options with this code.

    #+begin_src csharp

{
     "compilerOptions": {
     ...
     "target": "ES2015"
     },
     ...
     }

    #+end_src
     
  4. Run the application and test if the Essential JS 2 calendar component will render in the web browser.

*Source:*
- [[https://ej2.syncfusion.com/aspnetmvc/documentation/getting-started/visual-studio-2017#using-visual-studio-2019]]
- [[https://ej2.syncfusion.com/aspnetmvc/documentation/common/how-to/troubleshoot]]
