#+title:    Christian Faith
#+author:   h4ss4n
#+date:     <2023-09-18 lun.>

* Index
- [[Bible]]
  + [[Preservation][Preservation]]
- [[Refutal][Refutal]]

* Content

** Bible

*** Preservation


** Refutal

*** Rape allowed

The argument for Deutronomy 22:28-29 is debunk in the previous verses Deutronomy 22:25-27 were the punishment for rape was death.

Moreover, the verse says "if they be found (i.e., caught. this same word is used for a thief who is caught in Exodus 22:2) presupposes both parties are guilty of the act. So this cannot be rape but consensual sex (fornication).

Let's see the original Bible word in Hebrew, is "u·te·pa·sah" which is "seize" is not the same word used for rape. This a mistranslation found in the NIV (New Standrad Version).

Sometimes combine with Exodus 22:16-17 about men who seduces (ye·pat·teh) women not pledged in marriage, taking it out of context. The verse is about making a scoundrel responsible for his action not about forcing marriage with a rapist.

*** Women outcast

The argument for 1 Corinthians 14:34-35 is debunk in the previous verses 1 Corinthians 14:26-33 the whole chapter is about "speaking in tongues"

Paul's advice was about maintaining order in the church because the gifted saints began to become the place like a market (all talking at the same time in unknown languages).

Although women in that time didn't have a leadership role they occupied other roles and help men as shown in Romans 16:1-12 and Philippians 4:1-2

Also to debunk the claim is Ephesians 5:25 even when the hierarchy is from Christ -> Men -> Women is commanded to "submit to one another"

*** Association with mythologies

The claim to Christianity being like the Greek mythology "Zeus, wife, son", fall short because there's not such thing of God having sex in the Biblw. Just immaculate conception.
