#+title:    Christian Faith
#+author:   h4ss4n
#+date:     <2023-09-18 lun.>

* Index
- [[Bible]]
  + [[Preservation][Preservation]]
- [[Refutal][Refutal]]
  + [[Trinity][Trinity]]
  + [[Apostles][Apostles]]
    - [[Paul][Paul]]
  + [[Rape allowed][Rape allowed]]
  + [[Women outcast][Women outcast]]
  + [[Association with mythologies][Association with mythologies]]

* Content

** Bible

*** Preservation


** Refutal

*** Christians

**** Behavior

- Christians are called to expose evil, not just sit around and do nothing >> (Ephesians 5:11-12)

- Jesus in Christianity teached "love your enemies" >> (Matthew 5_44)

- We love Muslims, we don't like Islam it comes from evil, it turns people blinded and hateful version of themselves.

*** Trinity

**** The persons of the Trinity

- God: The Father, The Son and The Holy Ghost >> (Matthew 28:19)

- Reference of the three persons being one >> (1 John 5:7)

**** God (The Father)

- God The Father (Torah/Bible) it's a spiritual being and when we talk about Jesus being God’s Son it's in the sense that He is God (word) made manifest in human form (John 1:1; John 1:14) not in the sense of a human father and a son.

  And for the rest of us, we are adoptives "spiritual sons"... again not in the human way (as seems that you expect).
  We as children of God >> (Isaiah 64:7) (1 John 3:1)

**** Jesus (The Son)

- In the beginning (Elohim, masculine plural) >> (Genesis 1:1)

  It include Jesus (The Son), sometimes dismiss for the "Royal Plural" often asserted but never proved.
  The Royal Plural, is a medieval tradition that arose later, there's no evidence before & during the time of Christ that such linguistic feature was in usage.

  This is the same for Islam.

- I am the Alpha & Omega >> (Revelation 22:13)

*** Apostles

**** Paul

*** Rape allowed

The argument for Deutronomy 22:28-29 is debunk in the previous verses Deutronomy 22:25-27 were the punishment for rape was death.

Moreover, the verse says "if they be found (i.e., caught. this same word is used for a thief who is caught in Exodus 22:2) presupposes both parties are guilty of the act. So this cannot be rape but consensual sex (fornication).

Let's see the original Bible word in Hebrew, is "u·te·pa·sah" which is "seize" is not the same word used for rape. This a mistranslation found in the NIV (New Standrad Version).

Sometimes combine with Exodus 22:16-17 about men who seduces (ye·pat·teh) women not pledged in marriage, taking it out of context. The verse is about making a scoundrel responsible for his action not about forcing marriage with a rapist.

*** Women outcast

The argument for 1 Corinthians 14:34-35 is debunk in the previous verses 1 Corinthians 14:26-33 the whole chapter is about "speaking in tongues"

Paul's advice was about maintaining order in the church because the gifted saints began to become the place like a market (all talking at the same time in unknown languages).

Although women in that time didn't have a leadership role they occupied other roles and help men as shown in Romans 16:1-12 and Philippians 4:1-2

Also to debunk the claim is Ephesians 5:25 even when the hierarchy is from Christ -> Men -> Women is commanded to "submit to one another"

*** Association with mythologies

The claim to Christianity being like the Greek mythology "Zeus, wife, son", fall short because there's not such thing of God having sex in the Biblw. Just immaculate conception.
