#+title:    Dired Mode Basics
#+author:   h4ss4n
#+date:     2022-08-07 dom

* Inside Emacs GUI

- The Directory Editor (Dired) is the main mode for Emacs file-manager operations.
- Look for the top mark *Dired (directory)* instead of *Find file*.
- Open the *Evil Menu* by pressing ~g~ to display the key commands.

** Enter Dired

#+begin_quote

    SPC o - = open dired buffer

#+end_quote

- Every file opened in Dired, even by the minibuffer generate more buffers in memory.

** Movement

#+begin_quote

    C-j = move down (in mini-buffer)
    C-k = move up (in mini-buffer)

    j = move down
    k = move up

#+end_quote

** Operations

- Use ~M-RET~ to display a preview of the file without exit dired, move to other file and press again to watch.
- To delete the preview window press ~C-x 1~

#+begin_quote

    RET = enter a directory
    - = exit a directory

    m = mark/select a directory (or file)
    u = unmark/unselect a directory (or file)

    C = copy a folder/file (specify output path)
    R = rename a folder/file (don't forget the file extension in the end)
    D = delete a folder/file

    q = delete all dired windows (including the current one)

#+end_quote

- To *move* a folder/file don't specify a new name with ~R~, instead select the path to move and hit ~RET~.
- By default dired delete the files permanently, to avoid issues move to the trash can by adding to the =config.el=

  #+begin_src emacs-lisp

    (setq delete-by-moving-to-trash t)

  #+end_src
