#+title:    Doom Basics
#+author:   h4ss4n
#+date:     2022-07-26 mar

* Inside Emacs GUI

** General

*** Check the current version

#+begin_quote

    SPC h d v = version of emacs & doom

#+end_quote

*** Check for crashes

Provide by an uptime counter

#+begin_quote

   M-x emacs-uptime

#+end_quote

** Look for Help

*** Access to info manuals

#+begin_quote

    SPC h i = show a list of avaliable manuals

#+end_quote

*** Describe a key

#+begin_quote

    SPC h k = describe functionality and keybindings

#+end_quote

** Configuration

*** Open your Doom configuration files

- Let you access to the '.doom.d' folder and the files inside it.

#+begin_quote

    SPC f p = find/open private config

#+end_quote

*** Reload the configuration files

- Once edited and saved the files, it's possible to reload it even with Emacs still open.
  The equivalent of Doom Sync outside Emacs.

#+begin_quote

    SPC h r r = doom reload (plus RET to run it)

#+end_quote

- To changes take effect, close all Emacs instances and open it again.

**** TODO try this with Emacs client (closing the server and clients?)

** Managing Files and Directories

*** Find/open a file

- To create a new file select the location, type the name and file extension.

- To create a new folder select the location, the name of the folder and a '/' at the end.
  This will open a new scratch buffer if a file to be created is not especified.

#+begin_quote

    SPC f f = find/open a file
    SPC f r = open recent file
    SPC f s = save a file

#+end_quote

** Managing Buffers

#+begin_quote

    SPC b x = pop up scratch buffer
    SPC b b = switch workspace buffer
    SPC b i = move through buffers (select with hjkl and RET)
    SPC b k = kill buffers

#+end_quote

** Managing Windows

#+begin_quote

    C-x 0 = close the current window
    C-x 1 = current window fill the frame

    C-x 2 = horizontal split
    C-x 3 = vertical split

#+end_quote


** Text Editor

*** Evil commands

Uses the Vim keybindings

**** Move through text

#+begin_quote

    ESC = enter normal mode (to move)

    j = move cursor down
    k = move cursor up
    h = move cursor left
    l = move cursor right

    w = go to next word's beginning
    b = go to previous word's beginning
    e = go to next word's end
    ge = go to previous word's end
    [number] + [h/l] = go to letter/word number column

    0 = go to line's beginning
    $ = go to line's end
    % = jump to matching brackets {} [] ()

#+end_quote

**** Move through page

#+begin_quote

    gg = go to page's top
    G = go to page's bottom
    [number] + G = go to page's number row
    [number] + [j/k] = go to page's relative number row

    zt = scroll line to screen's top
    zz = scroll line to screen's middle
    zb = scroll line to screen's bottom

    C-y = move view pane up
    C-e = move view pane down
    C-u = move half-page up
    C-d = move half-page down

    C-o = jump to last pointer position
    C-i = jump to next pointer position

#+end_quote

**** Edit text

#+begin_quote

    i = enter insert mode (before letter down cursor)
    v = enter visual mode (to select text)
    a = append after letter (down cursor)
    A = apprend last word of the line

    O = create a new space above
    o = create a new space below

    x = delete
    d = cut
    dd = cut all the line
    y = copy (for use inside Vim)
    "*y = copy (for use outside Vim)
    p = paste

    u = undo
    C-r = redo

    c + [movement/operator] = change
    c + i + [text object] = change inner word/sentence/paragraph/etc
    c + a + [text object] = change around word/sentence/paragraph/etc
    cc = change all the line
    r = replace
    . = repeat the last change

#+end_quote

**** Increase/decrease letter case

#+begin_quote

    gu = make all line lower letters (RET to apply)
    gU = make all line upper letters (RET to apply)
    [select text] + u = make selection lower letters
    [select text] + U = make selection upper letters

#+end_quote

**** Search through text

#+begin_quote

    f + [letter] = find next
    F + [letter] = find previous
    t + [operator/text object] = until next
    T + [operator/text object] = until previous
    / = search word
    n = go to next find
    N = go to previous find

#+end_quote

*** Emacs commands

#+begin_quote

    C-g = cancel enter command (get me out)

#+end_quote
