#+title:    Doom Basics
#+author:   h4ss4n
#+date:     2022-07-26 mar

* Inside Emacs GUI

** General

*** Check the current version

#+begin_quote

    SPC h d v = version of emacs & doom

#+end_quote

*** Print the Working Directory

#+begin_quote

    M-x pwd = show the path

#+end_quote


*** Check for crashes

Provide by an uptime counter

#+begin_quote

   M-x emacs-uptime

#+end_quote

** Configuration

Your private config is kept in =~/.doom.d/= and it's typically comprised of an =init.el=, =config.el= and =packages.el= file.

- Put all your config in =config.el=
- Install packages by adding ~package!~ declarations to =packages.el=
- Enable/disable modules in your ~doom!~ block in your =init.el=

*WARNING*: You shouldn't need to fork Doom or modify =~/.emacs.d=. If you have to do this to achieve something, it can be considered a bug.

*** Switching to relative line numbers (permanently)

To change the style of line numbers, change the value of the ~display-line-numbers-type~ variable.

#+BEGIN_SRC elisp

    ;;; add to ~/.doom.d/config.el
    (setq display-line-numbers-type 'relative)

#+END_SRC

*** Add the Evil Tutor

#+begin_src elisp

    ;;; add to ~/.doom.d/packages.el
    (package! evil-tutor)

#+end_src

** Look for Help

*** Info manuals

For beginners, non technical background required.

#+begin_quote

    SPC h i = show a list of avaliable manuals

#+end_quote

**** TODO insert a link here with the org file 'InstallInfoManuals.org'

**** Info Mode Keybindings

- The letter 'g' act as a leader key in this mode (press it to display more options).
- The nodes acts like pages on a book.

#+begin_quote

    gT = main table of content
    gm = quick access to menu references (only works on top node)
    gG = quick access to nodes by name

    u = goes up one level to a parent node

    gj = next node
    gk = previous node

    g] = next reference (link)
    g[ = previous reference (link)

#+end_quote

*** Apropos

- Helps you narrow an area to search by name (plus regular expressions).
- Great for discover new commands.

#+begin_quote

    SPC h a + [command] + [query] = display a list of matching commands

    SPC h a + [variable] = display a list of matching variables

#+end_quote

- Useful for investigate new modes and package.

  #+begin_quote

    M-x apropos-library + [query] = list all functions and variables in a library

  #+end_quote

*** The Describre System

Some thecnical knowledge required.

- Helps to double check the information acquired.
- Describe your *personalized* Emacs.

**** Describe a mode

#+begin_quote

    SPC h m = describe current major mode (plus minor modes and keybindings)

#+end_quote

**** Describe a function (command)

Related to the M-x actions, once prompted enter the name to search.

#+begin_quote

    SPC h f = describe what a function does it

#+end_quote

**** Describe a variable

#+begin_quote

    SPC h v = describe what a variable does it

#+end_quote

**** Describe a key

Related to C-, M-x or SPC actions, once prompted enter the key combination.

- Some keys come from major and minor modes (are not global).
- The info may vary depending on the buffer you're in.

#+begin_quote

    SPC h k = describe what a keybinding does it

#+end_quote

** Configuration

*** Open your Doom configuration files

- Let you access to the '.doom.d' folder and the files inside it.

#+begin_quote

    SPC f p = find/open private config

#+end_quote

*** Reload the configuration files

- Once edited and saved the files, it's possible to reload it even with Emacs still open.
  The equivalent of Doom Sync outside Emacs.

#+begin_quote

    SPC h r r = doom reload (plus RET to run it)

#+end_quote

- To changes take effect, close all Emacs instances and open it again.

**** TODO try this with Emacs client (closing the server and clients?)

** Managing Files and Directories

*** Find/open a file

- To create a new file select the location, type the name and file extension.

- To create a new folder select the location, the name of the folder and a '/' at the end.
  This will open a new scratch buffer if a file to be created is not especified.

#+begin_quote

    SPC f f = find/open a file
    SPC f r = open recent file
    SPC f s = save a file

#+end_quote

- To *save as* a file with another name, inside a existing saved file press ~SPC f S~ being the last a upper case letter.

- To *save a scratch buffer* as a file with ~SPC f s~, first it's needs to have some content.

** Managing Buffers

#+begin_quote

    SPC b x = pop up scratch buffer

    SPC b b = switch buffers, show current ones (select with arrows)
    SPC b i = switch buffers, show everything (select with hjkl/arrows)
    SPC b p = switch to previous buffer
    SPC b n = switch to next buffer

    SPC b k = kill the current buffer
    C-x k = kill buffers (show a list, select with arrows)

#+end_quote

** Managing Windows

#+begin_quote

    C-x 0 = close the current window
    C-x 1 = current window fill the frame

    C-x 2 = horizontal split
    C-x 3 = vertical split

    C-x o = go to next window
    SPC w j = go to down window
    SPC w k = go to up window
    SPC w h = go to left window
    SPC w l = go to right window

#+end_quote

** Text Editor

*** Evil commands

Uses the Vim keybindings

**** Move through text

#+begin_quote

    ESC = enter normal mode (to move)

    j = move cursor down
    k = move cursor up
    h = move cursor left
    l = move cursor right

    w = go to next word's beginning
    b = go to previous word's beginning
    e = go to next word's end
    ge = go to previous word's end
    [number] + [h/l] = go to letter/word number column

    0 = go to line's beginning
    $ = go to line's end
    % = jump to matching brackets {} [] ()

#+end_quote

**** Move through page

#+begin_quote

    gg = go to page's top
    G = go to page's bottom
    [number] + G = go to page's number row
    [number] + [j/k] = go to page's relative number row

    zt = scroll line to screen's top
    zz = scroll line to screen's middle
    zb = scroll line to screen's bottom

    C-y = move view pane up
    C-e = move view pane down
    C-u = move half-page up
    C-d = move half-page down

    C-o = jump to last pointer position
    C-i = jump to next pointer position

#+end_quote

**** Edit text

#+begin_quote

    i = enter insert mode (before letter down cursor)
    v = enter visual mode (to select text)
    a = append after letter (down cursor)
    A = apprend last word of the line

    O = create a new space above
    o = create a new space below

    x = delete
    d = cut
    dd = cut all the line
    y = copy (for use inside Vim)
    "*y = copy (for use outside Vim)
    p = paste

    u = undo
    C-r = redo

    c + [movement/operator] = change
    c + i + [text object] = change inner word/sentence/paragraph/etc
    c + a + [text object] = change around word/sentence/paragraph/etc
    cc = change all the line
    r = replace current word
    R = replace various words
    . = repeat the last change

#+end_quote

**** Increase/decrease letter case

#+begin_quote

    gu = make all line lower letters (RET to apply)
    gU = make all line upper letters (RET to apply)
    [select text] + u = make selection lower letters
    [select text] + U = make selection upper letters

#+end_quote

**** Search through text

#+begin_quote

    f + [letter] = find next
    F + [letter] = find previous
    t + [operator/text object] = until next
    T + [operator/text object] = until previous
    / = search word
    n = go to next find
    N = go to previous find

#+end_quote

**** Delete all the conent

#+begin_quote

    gg + dG = go to first line and delete everything

#+end_quote

*** Emacs commands

#+begin_quote

    C-g = cancel enter command (get me out)

#+end_quote
