#+title:    Muhammad
#+author:   h4ss4n
#+date:     <2023-09-16 sáb.>

* Index

- [[Biography][Biography]]
  + [[Before-Islam][Before-Islam]]
  + [[After-Islam][After-Islam]]
- [[Wives][Wives]]
  + [[1. Khadija bint Khuwaylid][1. Khadija bint Khuwaylid]]
  + [[2. Sawdah bint Zam'ah][2. Sawdah bint Zam'ah]]
  + [[3. A'ishah bint Abi Bakr (Aisha)][3. A'ishah bint Abi Bakr (Aisha)]]
  + [[4. Hafsa bint Umar][4. Hafsa bint Umar]]
  + [[5. Zaynab bint Khuzayma (Umm al-Masakin)][5. Zaynab bint Khuzayma (Umm al-Masakin)]]
  + [[6. Hind bint Abi Umayya (Umm Salama)][6. Hind bint Abi Umayya (Umm Salama)]]
  + [[7. Zaynab bint Jahsh][7. Zaynab bint Jahsh]]
  + [[8. Juwayriya bint al-Harith][8. Juwayriya bint al-Harith]]
  + [[9. Umm Habibah Ramla bint Abi Sufyan (Umm Habiba)][9. Umm Habibah Ramla bint Abi Sufyan (Umm Habiba)]]
  + [[10. Safiyya bint Huyayy][10. Safiyya bint Huyayy]]
  + [[11. Maymunah bint al-Harith al-Hilaliyyah][11. Maymunah bint al-Harith al-Hilaliyyah]]
  + [[12. Rayhana bint Zayd*][12. Rayhana bint Zayd*]]
  + [[13. Maria al-Qibtiyya*][13. Maria al-Qibtiyya*]]
- [[Umah (Gang)][Umah (Gang)]]
- [[Unholiness][Unholiness]]
- [[Crimes][Crimes]]
- [[War][War]]
- [[Death][Death]]

* Content

** Biography

*** Before-Islam

**** Polytheism nº1

- Allah has 3 daugthers (al-Lat, al-Uzza and al-Manat) >> (Quran 53:19-21)

**** Arabs

- *In response of:* Arabs pagans killing their daugthers
  + *The problem:* Their own sources debunk that claim

    Is a false statement root in a bad interpretation to defend the bad threatment of muslim women (before it was worse).

*** After-Islam

**** Polytheism nº2

- Inside houses there were statues >> (Sahih Muslim 2109c, 2110a)

**** Prophethood

- Muhammad is only a warner >> (Quran 38:65)

- Muhammad don't know what will happen with him or others (afterlife) >> (Quran 46:9)

**** Prophecies

- The spliting of the moon went towards the mountain (more likely an eclipse) >> (Sahih Muslim 2802a, b)
  + Nowadays the moon is still intact. If the moon were to somehow split into two pieces, this could lead to widespread and devastating effects on the Earth's environment, including massive tidal waves and shifts in the Earth's axis, which would result in extreme climate changes.

- Or the Last Hour that would come before a kid present in his time grow old >> (Sahih Muslim 2952)
  + The kid died centuries ago, we are still here.


** Wives

*** 1. Khadija bint Khuwaylid

*** 2. Sawdah bint Zam'ah

*** 3. A'ishah bint Abi Bakr (Aisha)

- After Muhammad death:
  + She slept with at least 5 people, recorded.
  + She used her slave girl to hunt the youth of Kureish
  + Her blanket get semen from other men >> (Sunan Ibn Majah 538)

*** 4. Hafsa bint Umar

- *In response of:* The the ban on honey (false prophecy/deception)
                    Muhammad's wife was shocked how did the Prophet knew what she had done behind his back.
  + *The problem:* Their own sources debunk that claim

  Muhammad was caught up (adultery) with one of his wife's (Hafsa Bint Umar) maid (Maria Qubtia). When he do it again, Hafsa was angry but conveniently the chapter of the "Prohibition" appear (At-Tahrim 1-2). She spread the news with his other wives who get angry too and ignored him, so he knew what happen and confronted her (At-Tahrim 3) and threaten them with divorce (no man can re-married the Prophet's wives, so starvation) and hell fire (At-Tahrim 5).

  They beg and he had "pitty" of them so he don't visit them for one month >> (Quran 4:34) (Sahih al-Bukhari 2468)

  Some time later, Maria got pregnant with a baby boy named Ibrahim who died with 2yo, ¿a punishment from the real God? >> (Sahih al-Bukhari 1303)

  _NOTE 1:_ Muslims try to cover the shame of this verse refering to the ban their Prophet imposed on himself about 'honey'. But it's easy to debunk once you have all the pieces together with their sources.

  _NOTE 2:_ Hafsa's dad (Umar Bin Al-Khattab) the Prophet father in law used to follow and peep the Prophet wives in the field (Al-Manasi) when they "go to the bathroom to poop" (Shahih Bukhari, Vol. 8, Book 74, No.257) and he get caught for one of them (Sauda).

  Then he reported to Muhammad (playing the victim card as women tempting men), and instead of getting upset and complain about his harassment (like any husband will do). The prophet conveniently reveal another chapter for =veiling of the women= (Tafsir Ibn Kathir, Quran 33:59) vs (Ephesians 5:25)

  _NOTE 3:_ One of the REQUIREMENTS to a true prophet's prophecy is, it must be committed to holiness.
  If you sin and use the name of God in vain to cover it up, no matter how you label it it doesn't came from Him >> (2 Peter 1:21)

  In summary *women wear hijab today as punishment* for the fault of dirty old men from the 7th century >> (Shahih Bukhari, Vol. 1, Book 8, No.395)

*** 5. Zaynab bint Khuzayma (Umm al-Masakin)

*** 6. Hind bint Abi Umayya (Umm Salama)

*** 7. Zaynab bint Jahsh

*** 8. Juwayriya bint al-Harith

*** 9. Umm Habibah Ramla bint Abi Sufyan (Umm Habiba)

*** 10. Safiyya bint Huyayy

- *In response of:* Muhammad never rape any woman
  + *The problem:* Their own sources debunk that claim

    Muhammad killed the family and husband of Safiyya bint Huyayy to be taken as a wive the same day >> (Sahih al-Bukhari 4211) (Sahih Ibn Habban 11/607)

*** 11. Maymunah bint al-Harith al-Hilaliyyah

*** 12. Rayhana bint Zayd*

*** 13. Maria al-Qibtiyya*


** Umah (Gang)


** Unholiness

*** Satanic verses

- Muhammad under total control of Satan >> (Sahih Muslim 2814a)

*** Madness

- Muhammad maked wudu in filth water (dead dogs, menstrual rags and garbage) >> (Sunan an-Nasa'i 326) vs (Revelation 22:13)

- Muhammad imagining that he has slept with his wives, and in fact he didn't >> (Sahih al-Bukhari 6063)

**** Weird knowledge

- Muhammad said: "The eyes are the leather strap of the anus" >> (Sunan Abi Dawud 203)

*** Lies

- Muhammad allowing to lie persistently >> (Tafsir Tanwîr al-Miqbâs min Tafsîr Ibn ‘Abbâs, Quran 3:28) (Riyad as-Salihin 249; Introduction, Hadith 249)

- The "Muhammad's Night Journey" to the Jerusalem Temple

  He traveled on the back of Buraq (a half mule-donkey with wings) from the Sacred Mosque (Masjid al-Haram in Saudi Arabia) to the Farthest Mosque (Masjid al-Aqsa in Jerusalem) alongside with Jibril, then he tied Buraq to the door, enter to the Temple and led the prophets in prayer (Abraham, Moses and Jesus) and then He ascended into the seventh heaven and later spoke to Allah, who agreed to lower the number of required prayers from 50 a day to 5 (which every Muslim prays nowadays) >> (Tafsir Ibn Kathir, Quran 17:1)

  ¿How is that possible if Masjid al-Aqsa in Jerusalem did not come into existence until 691 AD? when the fifth Umayyad caliph Abd al-Malik built it, several years later after Muhammad died (632 AD) >> (Al-Ratrout, H. A., The Architectural Development of Al-Aqsa Mosque in the Early Islamic Period, 2004) (Ibn Ishaq - Sirat Rasul Allah also known as 'The Life of the Prophet', 760 C.E.)

  Even when Umar ibn al-Khattab conquer Jeruslem (637 AD) the site of the Temple Mount where is stood was a waste dump and he had to clean it out first >> (Akram, Agha Ibrahim, The Sword of Allah: Khalid bin al-Waleed – His Life and Campaigns, 2004).

  So... What temple did Muhammad go?
  Also he never mention this event like a dream, vision or parable. But a REAL life event.

  If you go for "Quran ONLY" explanation not Tafsir or Hadith... you have the problem that it doesn't tell anything about which is the Sacred Mosque and the Farthest Mosque (names or locations), or SPECIFY anything about the mandatory 5 muslims prayers (Sahih Muslim 233c) leaving you only with 3.

  +Although Quran says it's perfectly clear and explains everything in it, then it contradict itself (not doing it) >> (Quran 12:111, 16:89, 6:114, 41:3, etc)

  Making all your numbered prayers to be BASED ON A LIE.

  _Sources_
  https://www.answering-islam.org/Shamoun/nightjourney.htm

** Crimes

*** Theft

- Muhammad stealing a red velvet cloth >> (Tafsir al-Jalalayn, Quran 3:161)


** War


** Death

- *In response of:* Muhammad claims of being a prophet
  + *The problem:* Their own sources debunk that claim

    The bodies of the Prophets do not decompose >> (Sunan Ibn Majah 1637)

    At the beginning not even his companions believe that Muhammad died >> (Ibn Hisham, 2/655)

    Muhammad body become to descompose and stink after three days of his death >> (Tareekh-al-Kabeer: 1/31)
