#+title:    Muhammad
#+author:   h4ss4n
#+date:     <2023-09-16 sáb.>

* Index

- [[Biography][Biography]]
  + [[Before-Islam][Before-Islam]]
  + [[After-Islam][After-Islam]]
- [[Wives][Wives]]
  + [[1. Khadija bint Khuwaylid][1. Khadija bint Khuwaylid]]
  + [[2. Sawdah bint Zam'ah][2. Sawdah bint Zam'ah]]
  + [[3. A'ishah bint Abi Bakr (Aisha)][3. A'ishah bint Abi Bakr (Aisha)]]
  + [[4. Hafsa bint Umar][4. Hafsa bint Umar]]
  + [[5. Zaynab bint Khuzayma (Umm al-Masakin)][5. Zaynab bint Khuzayma (Umm al-Masakin)]]
  + [[6. Hind bint Abi Umayya (Umm Salama)][6. Hind bint Abi Umayya (Umm Salama)]]
  + [[7. Zaynab bint Jahsh][7. Zaynab bint Jahsh]]
  + [[8. Juwayriya bint al-Harith][8. Juwayriya bint al-Harith]]
  + [[9. Umm Habibah Ramla bint Abi Sufyan (Umm Habiba)][9. Umm Habibah Ramla bint Abi Sufyan (Umm Habiba)]]
  + [[10. Safiyya bint Huyayy][10. Safiyya bint Huyayy]]
  + [[11. Maymunah bint al-Harith al-Hilaliyyah][11. Maymunah bint al-Harith al-Hilaliyyah]]
  + [[12. Rayhana bint Zayd*][12. Rayhana bint Zayd*]]
  + [[13. Maria al-Qibtiyya*][13. Maria al-Qibtiyya*]]
- [[Umah (Gang)][Umah (Gang)]]
- [[Unholiness][Unholiness]]
- [[Crimes][Crimes]]
- [[War][War]]

* Content

** Biography

*** Before-Islam

**** Polytheism nº1

- Allah has 3 daugthers >> (Quran, Chapter 53, Verses 19-21)

**** Arabs

- *In response of:* Arabs pagans killing their daugthers
  + *The problem:* Their own sources debunk that claim

    Is a false statement root in a bad interpretation to defend the bad threatment of muslim women (before it was worse).

*** After-Islam

**** Polytheism nº2

- Inside houses there were statues >> (Sahih Muslim 2109c, 2110a; Book 37, Hadith 152)


** Wives

*** 1. Khadija bint Khuwaylid

*** 2. Sawdah bint Zam'ah

*** 3. A'ishah bint Abi Bakr (Aisha)

- After Muhammad death:
  + She slept with at least 5 people, recorded.
  + She used her slave girl to hunt the youth of Kureish
  + Her blanket get semen from other men >> (Sunan Ibn Majah 538; Book 1, Hadith 272)

*** 4. Hafsa bint Umar

- *In response of:* The the ban on honey (false prophecy/deception)
                    Muhammad's wife was shocked how did the Prophet knew what she had done behind his back.
  + *The problem:* Their own sources debunk that claim

  Muhammad was caught up (adultery) with one of his wife's (Hafsa Bint Umar) maid (Maria Qubtia). When he do it again, Hafsa was angry but conveniently the chapter of the "Prohibition" appear (At-Tahrim 1-2). She spread the news with his other wives who get angry too and ignored him, so he knew what happen and confronted her (At-Tahrim 3) and threaten them with divorce (no man can re-married the Prophet's wives, so starvation) and hell fire (At-Tahrim 5).

  They beg and he had "pitty" of them so he don't visit them for one month >> (Quran, Chapter 4, Verse 34) (Sahih al-Bukhari 2468; Book 46, Hadith 29)

  Some time later, Maria got pregnant with a baby boy named Ibrahim who died with 2yo, ¿a punishment from the real God? >> (Sahih al-Bukhari 1303; Book 23, Hadith 61)

  _NOTE 1:_ Muslims try to cover the shame of this verse refering to the ban their Prophet imposed on himself about 'honey'. But it's easy to debunk once you have all the pieces together with their sources.

  _NOTE 2:_ Hafsa's dad (Umar Bin Al-Khattab) the Prophet father in law used to follow and peep the Prophet wives in the field (Al-Manasi) when they "go to the bathroom to poop" (Shahih Bukhari, Vol. 8, Book 74, No.257) and he get caught for one of them (Sauda).

  Then he reported to Muhammad (playing the victim card as women tempting men), and instead of getting upset and complain about his harassment (like any husband will do). The prophet conveniently reveal another chapter for =veiling of the women= (Tafsir Ibn Kathir, Quran, Chapter 33, Verse 59) vs (Ephesians 5:25)

  _NOTE 3:_ One of the REQUIREMENTS to a true prophet's prophecy is, it must be committed to holiness.
  If you sin and use the name of God in vain to cover it up, no matter how you label it it doesn't came from Him >> (2 Peter 1:21)

  In summary *women wear hijab today as punishment* for the fault of dirty old men from the 7th century >> (Shahih Bukhari, Vol. 1, Book 8, No.395)

*** 5. Zaynab bint Khuzayma (Umm al-Masakin)

*** 6. Hind bint Abi Umayya (Umm Salama)

*** 7. Zaynab bint Jahsh

*** 8. Juwayriya bint al-Harith

*** 9. Umm Habibah Ramla bint Abi Sufyan (Umm Habiba)

*** 10. Safiyya bint Huyayy

- *In response of:* Muhammad never rape any woman
  + *The problem:* Their own sources debunk that claim

    Muhammad killed the family and husband of Safiyya bint Huyayy to be taken as a wive the same day >> (Sahih al-Bukhari 4211; Book 64, Hadith 251) (Sahih Ibn Habban 11/607)

*** 11. Maymunah bint al-Harith al-Hilaliyyah

*** 12. Rayhana bint Zayd*

*** 13. Maria al-Qibtiyya*


** Umah (Gang)


** Unholiness

*** Madness

- Muhammad maked wudu in filth water (dead dogs, menstrual rags and garbage) >> (Sunan an-Nasa'i 326; Book 2, Hadith 2) vs (Revelation, Chapter 22, Verse 13)

*** Lies

- Muhammad allowing to lie persistently >> (Tafsir Tanwîr al-Miqbâs min Tafsîr Ibn ‘Abbâs, Quran, Chapter 3, Verse 28) (Riyad as-Salihin 249; Introduction, Hadith 249)

** Crimes


** War
