#+title:    Allah
#+author:   h4ss4n
#+date:     <2023-09-18 lun.>

* Index
- [[Characteristics][Characteristics]]
  + [[Only one][Only one]]
  + [[Self-sufficiency][Self-sufficiency]]
  + [[99 names][99 names]]
- [[Attributes][Attributes]]
  + [[Body][Body]]
- [[Jannah (Paradise)][Jannah (Paradise)]]
- [[Jahannam (Hell)][Jahannam (Hell)]]
- [[Creation][Creation]]
  + [[Mala'ikah (Angels) ][Mala'ikah (Angels)]]
    - [[Jibril (Gabriel)][Jibril (Gabriel)]]
  + [[Shaitans (Devils)][Shaitans (Devils)]]
    - [[Iblis (The Satan)][Iblis (The Satan)]]
    - [[Jinns (Genies)][Jinns (Genies)]]
  + [[Humans][Humans]]
    - [[Adam][Adam]]
    - [[Hawwa (Eve)][Hawwa (Eve)]]

* Content

** Characteristics

*** Only one

- *In response of:* Allah don't have wife or children
  + *The problem:* Their own sources debunk that claim

    Allah hate to have [[file:~/org/bible/polemics/islam/muhammad/muhammad.org::Polytheism nº1][daugthers]] but no sons.


  + *The problem:* The Quran contradicts the Quran

    If Allah want to have a son he'll find a woman of his kind >> (Tafsir Tafsir al-Jalalayn, Quran 21:17)
    - ¿Why Allah mention IF HE WISH, he can sleep with women?
      A claim from the truth God cannot be in vein (if a consort doesn't even exist)


  + *The problem:* Allah isn't "All-powerful" anymore

    Allah can't have a son without a girlfriend >> (Quran 6:101)


  + *The problem:* Allah have sex with himself

    Only Satan do that kind of things ¿rigth? >> (Riyad as-Salihin 1842) // Review source


- *In response of:* Allah being our father
  + *The problem:* Muslims see Allah as a physical being

    He hava eyes, chin, 2 right hands, 1 foot, etc (even the argument about Jesus being his son, they probably think that Allah need a partner for sex, because without one how to procreate?)... that's what Mohammed in his ignorance taught (he didn't understand about spiritual stuff).

    In Christianity is [[file:~/org/bible/apologetics/christian-faith/christian-faith.org::God (The Father)][different]].

*** Self-sufficiency

- *In response of:* Allah is self-sufficient and doesn't need anybody
  + *The problem:* Their own sources debunk that claim

  Allah need humans to sin to forgive them, and if they don't sin he erase them to create sinners >> (Sahih Muslim, Book 037, Number 6621)

*** 99 names


** Attributes

*** Word

- ¿Is the Word of Allah, Allah?
  + Muslim have 3 divines (Allah, his Word, his Knowledge)

*** Body

- Allah is physical being but Jesus is rejected

** Jannah (Paradise)


** Jahannam (Hell)

- *In response of:* Muslims don't go to hell (only non believers)
  + *The problem:* Their own sources debunk that claim

    Everyone will enter into hell, including Muslims. Allah will then bring out the god-fearing >> (Quran 19:70-72)
    Although in contradiction with itself >> (Quran 66:7-8)  (Quran 3:157-158, 169) (Quran 9:111) & (Sahih Al-Bukhari, Volume 2, Book 23, Number 342)

   Many Muslims have tried to deny that the text says that everyone will enter hell. They argue that the expression "go down" (wurood) doesn’t necessarily mean to enter hell, but it can also mean to pass through or over.

   Some will even argue that the text is simply saying that people will cross over hell into Paradise on a bridge called Sirat, even though the Quran nowhere alludes to such a bridge.

   _Sources:_

   https://www.answering-islam.org/Shamoun/muslims_in_hell.htm


** Creation

*** Mala'ikah (Angels)

**** Jibril (Gabriel)

- *In response of:* Jibril is the Holy Spirit
  + *The problem:* nowhere (Quran/Hadith) it's says angels are spirits/souls
    - separates Jibril from Allah, Angels, Humans... so it left the genie >> (Quran 2:98)
    - angels have 2 to 4 wings in Quran (Quran 35:1)
    - in Hadith Jibril has 600 wings, contrdicts the Quran (Sahih al-Bukhari 4856)


  + *The problem:* Jibril comes also as a man
    - and angel as the same time)" >> (Quran 19:17)

*** Shaitans (Devils)

**** Iblis (The Satan)

- *In response of:* Satan as the one who deceive/lie
  + *The problem:* Their own sources debunk that claim

    Satan is also a muslim >> (Sunan an-Nasa'i 3960)

- Satan pissed in muslim ears >> (Sahih al-Bukhari 3270)

**** Jinns (Genies)

*** Human

- *In response of:* Islam scientific miracle -> reproduction
  + *The problem:* Allah don't know how humans are made of

    Men produce sperm in his backbone & women in her upper ribs (jugular notch) >> (Tafsir al-Jalalayn, Quran 86:7)

**** Adam
**** Hawwa (Eve)
