#+title:    Jesus
#+author:   h4ss4n
#+date:     <2022-12-31 sáb.>

* Index

- [[Refutal][Refutal]]
  + [[Where Jesus says "¿I am God?"][Where Jesus says "¿I am God?"]]
  + [[Jesus lost years][Jesus lost years]]

* Content

** Refutal

*** Where Jesus says "¿I am God?"

_NOTE 1:_ When they use John's Gospel to prove that Jesus was only a man.

John firstly introduce Jesus as the "Word" of God, the bridge between the transcendent God and the world.

But John goes even beyond and presents Jesus not as a mere mediating principle, but as a personal being, fully divine, yet fully human. (John 1:14)

In John's use of the Word concept, we find that:

-Jesus is eternal ("In the beginning was the Word")
-Jesus was with God prior to coming to earth ("the Word was with God")
-Jesus is God ("the Word was God.")
-Jesus is Creator ("All things were made through him")
-Jesus is the Giver of Life ("In him was life")
-Jesus became human to live among us ("the Word became flesh and dwelt among us")

Just God existed before human kind, and even so Jesus says "Before Abraham Was, I Am" >> (John, Chapter 8, Verse 58)

Also, Jesus was not simply a personification of God's revelation as the Jews thought, but was indeed God's perfect revelation of Himself in the flesh. (John 14:9)

"The Word of God take form of a humble man" >> (John, Chapter 14, Verse 28)

*** Jesus lost years

From 12 to 30 years old, Jesus get his knowledge from pagan places (India, Japan & Britain)

~Time Line Start~

**** Birth
- Jesus born in the City of Bethlehem (Luke 2:1-6)
- His family has to escape to Egypt for a brief period of time (Matthew 2:19)
- Later he came back to Nazareth (Matthew 2:21-23, Luke 2:39)
- His learning was also in Nazareth (Luke 2:51-52)

**** 12 years old
- He was lost in the feast of the passover and he was found in the Temple speaking with sages (Luke 2:41-51)

**** From 12 to 30 (18 years span)
He took care of his family:
- In jewish tradition boys from 12 yo are taken as adults and his father is responsable to teach him a craft,
  so he don't end in a bad path
- Jesus will work for his family setting up his part of the business (his own clientele, specialty, etc)
- Joseph died during this period of time, leaving at least 5 sons and 2 daugthers (besides Jesus)
  (Matthew 12:46, Luke 8:19, Mark 3:31, Matthew 13:55-56, John 7:1-10, Acts 1:14, Galatians 1:19)
  + assuming 1 child per year, are 7 years were a widow would have to take care of infants without income
- a responsibility that Jesus take care for later go to his own ministry
  + according to his teachings you cannot be a leader in the house of God if you're not from your own home
- traveling for years will be imposible just by the state of poverty of his humble profession (Mark 6:3)
  + also in that time it was consider unclean for a jew joining with a foreigner (Acts 10:28),
    something he change after his death (Acts 11:17-20)
  + other reason is the danger of traveling alone, it's better to travel in a group of jews
    - he could use his power for protection, but he kept his profile low until he began his ministry (John 2:1-11)

**** 30 years old
- Jesus was baptized in the Jordan River by Jhon (Mark 1:9)
- He came back a saturday to Nazareth to read in the synagogue, an habit made by years (Luke 4:16)

~Time Line End~

His teachings are in conflict/contradiction with other faiths:

_About the reincarnation cycle_
  + when you die the salvation come through faith of believe in Him not by your actions (John 3:18, 3:36)
  + you go from death to eternal live, not through a reincarnation cycle

_About empty the mind_
  + an important point in Eastern teachings, which Jesus warn us to avoid for its dangers
  + when an evil spirit it's cast out, it can bring 7 more because the body is empty (Mathew 12:43-45, Luke 11:24)

_About one God only_
  + Jesus don't believe in various gods but one to worship (Mark 12:29)

_About different paths to heaven_
  + the various ways of thinking that unites us (John 14:6)

_A reliable source_
  + The Gospel of Luke by it own nature its the more historical one and had a lot of details, 119 of the 186 events
